- name: Install systemd service
  become: yes
  template:
    src: templates/vault.service.j2
    dest: /usr/lib/systemd/system/vault.service
  notify:
    - reload systemd daemons
    - restart vault

- name: Enable vault daemon
  become: yes
  when: not ansible_check_mode
  systemd:
    name: vault
    daemon_reload: yes
    enabled: yes
  notify: restart vault
