- name: "Add the {{ vault.user }} user"
  become: true
  user:
    create_home: no
    system: yes
    shell: /sbin/nologin
    name: "{{ vault.user }}"
    state: present

- name: "Add {{ vault.user }} user to {{ user.group }} group"
  become: true
  user:
    name: "{{ vault.user }}"
    groups: "{{ user.group }}"
    append: yes

- name: Install vault
  when: needs_install
  become: yes
  unarchive:
    remote_src: yes
    src: "https://releases.hashicorp.com/vault/{{ config.services.vault.version }}/vault_{{ config.services.vault.version }}_linux_{{ golang_artifact_arch }}.zip"
    dest: "{{ vault.bin | dirname }}"
    owner: "{{ vault.user }}"
    group: "{{ user.group }}"

- name: configure systemd
  include_tasks: _systemd.yml
