# an encryption key for all consul messaging
encryption_key: !!secret
# long story, but one of the original servers had 8500 taken :/
ports:
  dns: 5553
  http: -1 # disable http
  https: 5554
  grpc: -1 # disable grpc
  grpc_tls: 8503 # default port
  serf_lan: 5551
  serf_wan: 5552
  server: 5550
version: 1.16.2
# this is the global management token
token: !!secret
