# configures the internal dns resolver
consul:
  # used by dns service to read services and stuff
  token: !!secret
# send upstream queries to these servers
forwarders:
  - tls://1.1.1.1
  - tls://8.8.8.8
provider: digitalocean
# the fully qualified domain name for my nidito
# it's expected to have publicly routable addresses for every subdomain
zone: tepetl.net
# resolves DNS for ACME requests
acme_resolver: ns1.digitalocean.com
