- name: Reload nomad config
  when: ansible_service_mgr == "launchd" and not restarted_service.changed
  listen: reload nomad
  become: yes
  shell: kill -HUP "$(ps x | awk '/\/usr\/local\/bin\/nomad agent/ {print $1; exit}')"

- name: Reload nomad config
  when: ansible_service_mgr == "systemd" and not restarted_service.changed
  listen: reload nomad
  become: yes
  systemd:
    name: nomad
    state: reloaded
