- name: Restart nomad service
  when: ansible_pkg_mgr == "homebrew"
  listen: restart nomad
  become: yes
  shell: "launchctl stop io.nomad.daemon 2>/dev/null; launchctl load -w /Library/LaunchDaemons/io.nomad.daemon.plist"

- name: Restart nomad service
  when: ansible_pkg_mgr == "pacman"
  listen: restart nomad
  become: yes
  systemd:
    name: nomad
    state: reloaded

- name: Restart nomad service
  when: ansible_pkg_mgr == "unknown"
  listen: restart nomad
  become: yes
  shell: /usr/syno/bin/synopkg restart nomad || /usr/syno/bin/synopkg start nomad
