summary: Writes config to 1password
description: |
  Will either create or update existing items with a matching name. Uses https://1password.com/downloads/command-line/ and can talk to 1password.com or an `OP_CONNECT_HOST`.

  ## Invariants:

  - one 1password (op) item per config file
  - `password` field contains md5sum of source file
  - one text field per value (secret or not)
  - uses dot notation for keys, so these should only contain [a-Z0-9_-]
  - arrays stored as `.index.`, i.e. `.0.`
  - non-string scalar types (bool, int, float, and null) stored as under the `~annotations` section with the same key name

  ## Caveats
  - text with newlines is not properly editable in 1password: newlines are broken on 8/mac and browser is wonky with newlines
arguments:
  - name: name
    description: The config name(s) to flush. If unspecified, all configs will be flushed
    variadic: true
    values:
      milpa: nidito config list --source names
options:
  dry-run:
    description: don't write changes, only show what would happen
    type: bool
