summary: Retrieves configuration keys
description: |
  Lists the names (`dc:casa`), files (`dc/casa.yaml`) or 1Password item names where config is available.
options:
  source:
    default: names
    description: the source to query config from
    values: {static: [files, names, op, vault]}
