- name: "Install wireguard"
  pacman:
    name: wireguard-tools
    state: present
  notify: restart wireguard

- name: Install wireguard config
  template:
    src: "templates/wg0.conf.j2"
    dest: "/etc/wireguard/wg0.conf"
    mode: u=rw,g=r,o=
  notify: restart wireguard

- name: Enable wg-quick daemon
  become: yes
  systemd:
    name: wg-quick@wg0
    daemon_reload: yes
    enabled: yes
  notify: restart wireguard
