- name: "Install wireguard"
  pacman:
    name: wireguard-tools
    state: present
  notify: restart wireguard

- name: Install wireguard config
  template:
    src: "templates/wg0.conf.j2"
    dest: "/etc/wireguard/wg0.conf"
    mode: u=rw,g=r,o=
  notify: restart wireguard

# https://wiki.archlinux.org/title/WireGuard#systemd-networkd
- name: Route main dns zone over vpn
  become: true
  shell: |
    resolvectl domain wg0 '~{{ config.datacenters[node.dc].dns.zone }}' '~42.10.in-addr.arpa'
    resolvectl default-route wg0 false
