- name: Get installed module version
  become: true
  shell: |
    modinfo wireguard | awk '/^version/ {print $2}'
  register: module_installed_version
  check_mode: no
  ignore_errors: yes

- name: Get installed tools version
  become: true
  shell: |
    /usr/bin/wg --version | awk '{sub("v", ""); print $2}'
  register: tools_installed_version
  check_mode: no
  ignore_errors: yes

- set_fact:
    needs_install: "{{ module_installed_version.stdout != edgeos_pkg_version or tools_installed_version.stdout != edgeos_tools_version }}"

- name: Create the wireguard directory
  become: true
  file:
    path: "/config/wireguard"
    state: directory
    owner: root
    group: vyattacfg
    mode: u=rwx,g=rwx,o=

- name: Get the latest installer
  when: needs_install
  get_url:
    url: https://github.com/WireGuard/wireguard-vyatta-ubnt/releases/download/{{edgeos_pkg_version}}-1/e300-v2-v{{edgeos_pkg_version}}-v{{edgeos_tools_version}}.deb
    dest: /config/wireguard/installer.deb
  register: new_installer

- name: Create the firstboot directory
  become: true
  file:
    path: "/config/scripts/firstboot.d"
    state: directory
    owner: root
    group: vyattacfg
    mode: u=rwx,g=rwx,o=

- name: Install wireguard firstboot.d script
  become: true
  template:
    src: templates/post-config.sh.j2
    mode: u=rwx,g=rwx,o=rx
    dest: /config/scripts/firstboot.d/wireguard.sh
  register: config_install

- name: Run firstboot script
  when: config_install.changed or new_installer.changed
  become: true
  shell: /config/scripts/firstboot.d/wireguard.sh
