- name: Add the vault user
  become: true
  user:
    name: "{{ vault.user }}"
    create_home: no
    shell: /usr/bin/false
    groups: "{{ user.group }}"
    append: yes

- name: Install vault
  when: installed_vault_version.stdout != vault.version
  become: true
  unarchive:
    src: "https://releases.hashicorp.com/vault/{{ vault.version }}/vault_{{ vault.version }}_darwin_{{ golang_artifact_arch }}.zip"
    remote_src: yes
    dest: /usr/local/bin
  notify:
    - restart service


- name: Create the vault log directory
  become: true
  file:
    path: "{{ vault.logs }}"
    owner: "{{ vault.user }}"
    group: "{{ user.group }}"
    state: directory
    mode: u=rwx,g=rwx,o=
