- name: Restart vector service
  when: ansible_pkg_mgr == "homebrew"
  listen: restart vector
  become: yes
  shell: "launchctl stop dev.vector.daemon 2>/dev/null; launchctl load -w /Library/LaunchDaemons/dev.vector.daemon.plist"

- name: Restart vector service
  when: ansible_pkg_mgr == "pacman"
  listen: restart vector
  become: yes
  systemd:
    name: vector
    state: restarted

- name: Reload vector service
  when: ansible_pkg_mgr == "pacman"
  listen: reload vector
  become: yes
  systemd:
    name: vector
    state: reloaded

- name: Restart vector service
  when: ansible_pkg_mgr == "unknown"
  listen: restart vector
  become: yes
  shell: /usr/syno/bin/synopkg restart vector || /usr/syno/bin/synopkg start vector
