- name: Restart node_exporter service
  when: ansible_pkg_mgr == "homebrew"
  listen: restart node_exporter
  become: yes
  shell: "launchctl stop io.prometheus.node_exporter.daemon 2>/dev/null; launchctl load -w /Library/LaunchDaemons/io.prometheus.node_exporter.daemon.plist"

- name: Restart node_exporter service
  when: ansible_pkg_mgr == "pacman" or ansible_pkg_mgr == "unknown"
  listen: restart node_exporter
  become: yes
  systemd:
    name: node_exporter
    state: restarted

