consul:
  allowed_networks:
  - management
  - vpn
  encryption_key:
    ciphertext: utp3DmeQIpL6nB/6MBBekfDFvzd2tEFO/h002fSwzv5gkY8NVzCs2ANRoUBgLSnUMxaRuRcde/7Qj0uWCozMabcuooNMNE0KRIo4NZg/0LLTNIVad71vJ0dFyNs=
    encrypted: true
    hash: ab19fdadeee3cc7e14aff31d312643125003c7cecddd907d4cd716261cd14042
  ports:
    dns: 5553
    http: 5555
    serf_lan: 5551
    serf_wan: 5552
    server: 5550
  version: 1.8.3
crypto:
  key: nX447KScZXogkbfsFb755uhcwJULlGWwMFyO2Kikaztt2pzXawUCTgf5QHafd0HQ2s1Jh0hVKZgy13X33E95zwswVEc8mqpsrGPnCoh69V9+WlZRebonGR3fEds=
  provider: password
dns:
  external:
    # when resolving non ${dns.zone} queries, forward to
    forwarders:
    - 1.1.1.1
    - 8.8.8.8
    # our domain is a registered TLD whose NS point to:
    nameserver: ns1.digitalocean.com
    provider:
      name: digitalocean
      record-id: "62497256"
      token:
        ciphertext: zOmnwZv3HYGhn7kVhFD6IBy0tmE8xdb+bN/6Xria+HHqD3fnQ8L+GIfv6lsV+MYV9kKaCfCRTRUUC6x4BzOB+tDPg1BtG/lFMTSHpm/Q46IX8fhQ8jhcZSbq3UxXfMLDxePJev3sOEp0LjwlUKSdEA==
        encrypted: true
        hash: afe6d35ae8fbc96087e14c6c4afd1dede78c68013a158a87186a2b466a71cd62
  # the fully qualified domain name for my nidito
  # all services will be a subdomain of this domain
  zone: nidi.to
filebeat:
  config: /usr/share/filebeat
  user: root
  version: 7.4.0
home:
  location:
    elevation: 17
    lat: 40.686174
    lng: -73.930374
  time-zone: America/New_York
http:
  # zones are groups of networks referenced by consul services
  # using the `nidito-http-zone` meta field.
  zones:
    local:
    - management
    - vpn
    - shared
    public:
    - external
    trusted:
    - management
    - vpn
networks:
  external: 0.0.0.0/32
  # servers, trusted devices
  management: 10.10.0.0/24
  # guests and iot
  shared: 10.20.0.0/24
  # the network for network devices
  switch: 10.0.0.1/24
  vpn: 10.11.11.0/24
nodes:
  ajusco:
    address: 10.10.0.3
    consul:
      config: /etc/consul.d
      peers:
      - chapultepec
      - xitle
      token:
        ciphertext: EH2JSfIaQ0sMk28ekAO6I+8GmeRnu/5UY2m+tC+pzQ99S2Q1RAm2QEuKDWJ3C5SgwgN4nf0+WbkQqrupMATXcYo7IuYFXJUH/4iK03yc/pHcOPyx
        encrypted: true
        hash: 8b3935bd5bedb0253402a7184159196a16359556bbeab23ac1319a2aa018f522
      user: consul
    hardware: pixiepro
    mac:
      ciphertext: 7l8hjZ4Gzo3SPZbbhRNKIrwnix+EjSBM9pxxvtz/rvPYoT8XUxvYW/3NVld78cqL704HKoHvd5r7g6QO1V/K7f4=
      encrypted: true
      hash: f7462b010db2fce63c45774b5f71b49b9321d831c95607f0d789f89c30238a64
    nomad:
      config: /etc/nomad.d
      data: /var/lib/nomad
      user: root
    platform: linux/arch
    reachability: public
  brooklyn:
    _ansible:
      ansible_command_timeout: 120
      ansible_connection: ssh
      ansible_user: router
    address: 10.0.0.1
    dns:
      config: /home/coredns
      enabled: true
      mode: leader
    hardware: edgerouter-12p
    platform: linux/edgeos
    reachability: gateway
  chapultepec:
    address: 10.10.0.2
    consul:
      config: /etc/consul
      http_services:
        # chapultepec exposes its own admin panel stuff
        # publish that under dsm.nidi.to
        dsm:
          port: 5000
          zone: trusted
        plex:
          port: 32400
          zone: local
      peers:
      - ajusco
      - xitle
      token:
        ciphertext: E6stjH/KPhc7Pb4YTCZNPHjs4lMkH00E1/thLQvm1aYCEpIPg7Kmb/9NbAIksID2PFzhfpmNMlZh7Ayoo3QJdv5HpgHJ6Mq7fyWfmxqyXRh1u0j1
        encrypted: true
        hash: bff9d99ce97d8137bbce7b2a83d0b90060bfb0527e674b732f00ce30f24d9438
      user: root
    hardware: dsm918+
    mac:
      ciphertext: iBe2jQjz0Ue1XV9VL2tCVoaYn8jw0tl1vjqt7vyxc9TuWfgW34LMEMUpjTa3bhodU9Ra1/Nu6/PTH19PDAvff6A=
      encrypted: true
      hash: 51936351e6b2277c56c7b6424c1bf64e1d0ee694e5bcd6cdbadbb44ebb5fa9ab
    nomad:
      config: /etc/nomad
      data: /volume1/nomad
      memory: 8000
      meta:
        nidito-storage: primary
      user: root
    platform: linux/dsm
    reachability: private
  xitle:
    address: 10.10.0.4
    consul:
      config: /nidito/consul
      peers:
      - ajusco
      - chapultepec
      token:
        ciphertext: wheXSeQ+61jOZ8iY3vKd31hFoOlpnIYh8PCwelCpOqw5d+6EM+YlLBhakzpwjo9a1aQPC78CcoW0KkDDRo6ypEPlxsNwI8mbN1zDvlgA8Nza4sXf
        encrypted: true
        hash: 53e2ecb0758fd6b9575e247e78889da48274c51667656f57af780c4282754db5
      user: _consul
    hardware: mbp
    mac:
      ciphertext: HytShicxgywNDh0p41qWOLpE/CeACfz2wCOMx4GYlKNU8KOKSiEBH1UxtlxUJaOFKx0C04MRlOjgJoGqWDJiMDk=
      encrypted: true
      hash: 2174b10ed9202452bbb79213e316c40279880791dc005d7677ce37e8b36b1f29
    nomad:
      config: /nidito/nomad
      data: /private/var/lib/nomad
      memory: 10000
      user: root
    platform: macos
    reachability: private
    vault:
      config: /nidito/vault/config
      user: _vault
nomad:
  ports:
    http: 5560
    rpc: 5561
    serf: 5562
  token:
    ciphertext: 6t2f+D/Vly7BZ/N2JrRJ4NoR9UZN1JGsldvgDMuCzjZc3CNq1wBOUSP24CmgbbnEeDrbBqsYjk/rvwTaFlSzCtsZRzlKwiKKKsM=
    encrypted: true
    hash: 7c58186b3b631c6e96801ffdf12c627555608a9c8378fbcedcdd9a33493b65a6
  version: 0.12.4
router:
  interfaces:
    bonding:
    - description: chapultepec
      hash-policy: layer2
      mode: 802.3ad
    ethernet:
    - bond-group: bond0
      description: chapultepec 0
      vlans:
        untagged: 10
    - bond-group: bond0
      description: chapultepec 1
      vlans:
        untagged: 10
    - description: ajusco
      vlans:
        untagged: 10
    - description: xitle
      vlans:
        untagged: 10
    - description: "OFF"
      vlans:
        untagged: 20
    - description: Apoltivi
      vlans:
        untagged: 20
    - description: Hueberto
      vlans:
        untagged: 20
    - description: UAP
      vlans:
        untagged: 20
        tagged: 10
    - description: Emergency
      address: 192.169.1.1/24
    - description: Internet
      address: dhcp
      firewall in ipv6-name: WANv6_IN
      firewall in name: WAN_IN
      firewall local ipv6-name: WANv6_LOCAL
      firewall local name: WAN_LOCAL
    - description: "OFF"
    - description: "OFF"
    wan: eth9
  networks:
    default:
      address: 192.168.1.0/24
      lease: 86400
      size: 20
    guest:
      address: 10.20.0.0/24
      hosts:
      - name: Apoltivi
        address: 10.20.0.20
        mac:
          ciphertext: yiar7p2IroNyFz4kqBGXUapTTU48vu7jF/LLgeJuXlsf03d97w5bU2Loh8gdLJkmppcWvvgbwPm9J5eLIzr55/c=
          encrypted: true
          hash: 81e0033034e9646c61fce3f4b6ed9a943f563bee5d629a770eb9466368e51101
      - name: Hueberto
        address: 10.20.0.30
        mac:
          hash: 856261d46ca21d660926a776f097442010cc57a81d6ecf4372ff031c9eae1be3
          ciphertext: Sp9FWN+fI20VzXY9zt5SDdodeyGlsWFmCmEXUHH97DSx4cQ9HTfx5mDxEF5RwE82uVo/LQrHEkPvUOHzEtUzk9o=
          encrypted: true
      lease: 86400
      rules:
        default: drop
        in:
        - description: http
          action: accept
          destination group: address-group public-nodes
          destination port: port-group http
          log: disable
          protocol: tcp_udp
        - description: homekit
          action: accept
          destination group: address-group homekit
          log: disable
          protocol: all
        - description: all other traffic to trusted
          action: drop
          destination group: network-group trusted
          log: disable
          protocol: all
        local:
        - action: accept
          description: 'allow dns'
          destination: port 53
          log: disable
          protocol: tcp_udp
        - action: accept
          description: 'allow dhcp'
          destination: port 67
          log: disable
          protocol: udp
      size: 100
      vlan: 20
    trusted:
      address: 10.10.0.0/24
      hosts:
      - name: Tlaloc
        address: 10.10.0.10
        mac:
          hash: 81e0033034e9646c61fce3f4b6ed9a943f563bee5d629a770eb9466368e51101
          ciphertext: KczKLyf0e5LJtbX74vL4gXLMjUs63vpGeIXY8sIBEBWqb+flIjTkzfNGxJlgsiOewjrpcNLbeK3Pq5Vi3C/QEuE=
          encrypted: true
      - name: Chiquihuite
        address: 10.10.0.11
        mac:
          ciphertext: RByB3E3J5BFZtEBA6H0inSZxdlCE0WRkBYVWwvvfbInyo1e3jymVcSJW0EXPBvYGMLMv/AfT3AEMxKNe90Cr3do=
          encrypted: true
          hash: 3fae35c0adcb53afbf52ecd3bcbbc413f00edfac3ac6b8b92f826edc2d2d3c15
      - name: Citlaltepetl
        address: 10.10.0.12
        mac:
          ciphertext: nhWWi8bZP0SaNGDaJFeN1zejzpnssYnPLMAmAnbBvHG1SAHPr078yIYwpHIuwY4F64XNlJtfMbKmW7/hd9hBcI8=
          encrypted: true
          hash: 3460a45cbdd95e71fe2637afebc29db7a0292ff95f958c2c644c6d67458442d8
      - name: Zempoala
        address: 10.10.0.13
        mac:
          hash: 96862d63d71895072c91b99c059a1fa2238b23ad15071e0ae274faa0ed5dc664
          ciphertext: Oqh41T2/yUvzqf5Z8dUoEISEkiqX7bjA3o2faxhrFzbcbTnjcj0JZdPTY+03Q9LM3TQerEjclriRBl+BGnzQTuE=
          encrypted: true
      lease: 3600
      main: true
      rules:
        default: accept
        in: []
        local: []
      size: 100
      vlan: 10
services:
  frigidaire:
    email:
      ciphertext: kSAv36BU/pAfXeXmMdld8ZSMiSMWJ9pp/XXDiqcinCucuHmM2x5HDtRmrm0JBCJQLLCRl2oHJMqN
      encrypted: true
      hash: fdb94a6db49472fee8d0f1f737d9ba82fbd3e85591056fee0238f4ab96033b8a
    # It gets cold in winter
    enabled: true
    password:
      ciphertext: 7s0cv8YjN9d/ZWFtUCvyOr8igdSF9fIM9YI6Za/YeUJehCscp7J0Xhnp3723wRmTrFemAx9BniIQ0BwSULtV
      encrypted: true
      hash: bd87686fcb88e3b1ef1c0ca96dd14c182b6b6fccdc9e0cd27b3ac2b15d3717bf
    pin:
      ciphertext: WUSvblP5/svbY8Hylynuhinq5X/+DADePAi9JUSUyjep1f+BRf9ck6M/G5RqH+p09Ckkzu7JOlFVA6ox
      encrypted: true
      hash: 6f98c410748be2e7131147df2cafd578b7b12c74fd44ecf270cd837b2f021c36
  homebridge:
    nest:
      # landlord shuts down the whole system cause it's old
      enabled: false
      id:
        ciphertext: tK6VO4wGCSKJciydd7ieTgjybX/Idfn0ZkvPqrxKzfa9QDeHr8ftdtML+3OWVuIA0Cz/EXL21+tcYBZaO7tbW97Cn5rlVgFEJy2fRZvgiSvWBAW7
        encrypted: true
        hash: 87ad94cc992b2cb0c268e1b72025d0cb55eef5295064970e5878250c8d0a5c9f
      secret:
        ciphertext: /kd7jiok9TeWx1hrcxST3UEo4e0MlBpmiuN6wok2Nel5RZSjPtB5mncWb3RmGJwFZR+4IXbw86kYZMSYbWWJlj48nszxrFy/fA==
        encrypted: true
        hash: fa88cdaa0fb47270a2216955fda1471491fe7e9519e2c0de97290563b80f0a77
      token:
        ciphertext: pLPNW6skQVjm+EJqJzQpbEIlVu1o2ZLyf/1RwInAor3gK62xB0HVjVNlyYHapZKcrp/Xgq/ltV56pvjoQEANqa95QPQIDBUuwIR0UZS59wvLeoSl96gkOKwE62ppSP3Fu1T4WeB7OXLd/HPVAPnGaYk/IkVhMu5KZ1nFkT7OKvhjtBwZFY9HuM6jGL77GOYgZIMAiq1fnNU/cPIywh/+TUMKQ2FlvgxDJCUrXZgvkh3z5j3dMgnt6srm11E+qNYtYxc=
        encrypted: true
        hash: 1b01f3d119ca7fb1a8a02a2bf08c4fad9209bd04029b2a3dc0ed823d59f84a7a
    pin:
      ciphertext: WUSvblP5/svbY8Hylynuhinq5X/+DADePAi9JUSUyjep1f+BRf9ck6M/G5RqH+p09Ckkzu7JOlFVA6ox
      encrypted: true
      hash: 6f98c410748be2e7131147df2cafd578b7b12c74fd44ecf270cd837b2f021c36
    username: "13:37:D3:4D:B3:3F"
  icecast:
    credentials:
      admin:
        ciphertext: WY0uRSXzREIp8BnN5/HiXz6ajcYQMP3Qq8UTlfsQhpjfxzk7re00pbroD1JSnLfJBwTYnAsdFT08/tvmZKJI82ly2CD4lTRWc+aipNNcNy0=
        encrypted: true
        hash: 86292b0aa0220e62c96ce132cb2bba38b5af2c4f687a130ca0899078cf4250d1
      source:
        ciphertext: JgTJdC1NY+QQApE7UNKLZ5I/qZC8s2QSC4SzmJndK5612HDT/UBdxou3O+t7yhUN+c6lXhaZRL3CqW3dgVN09Qg=
        encrypted: true
        hash: 2221cb4077211a07b66143f4cd6cd885798355ac36c90a91c1502b0dc2098547
  letsencrypt:
    email: nidito@un.rob.mx
    private_key:
      ciphertext: guogw/RBOzsu3EIM10YrH/u1YaK/mZPBex7Y54SJ59FpUF/tWXgIBrTREFQGIS63ZYbb6feIJOLycp9g5rFZ7PqlWZ1SAgU8MwmmD9owuqanOJMeF1DXcigANUPYgRdvTaD4We5ClSfGcCybSwmDVqc0uIgsWJrQr19L4sli4YbDBgav3n59EZkBM+mSutc5SX1L/f83VPfX4Ckd1RfSwCc8I7p/Yyg4Pv2JfJNQROFQzdSp8LNk5ayUJWTVTI49rLkWgr86QVa0+i/SmxYm66U2l0uA94mpjmrkhMYNYFdP7GviPM9d2ZlS8CPEvxh52qJgSB41eaXd/U7Ebfzf3xBR3a8TSCMmjwKw21c03A1GK05emho7CyANej7vjwTUqJgONNsknN1FHN08d+lT5gKMRS0pBoRNETkI4QmF8O+uA1l98v1NChSpcx5N9JNv8sDWjGujPN7yzsaF3GmgEhdb0b6u6ogc2v+A5NfIGUnROfGRmbloyAWz0/3X8vsWbT+51ZTM8FU6s36lq1051kL8x+KLAzQ9rdnzqfFcj+um2L6LOEg+of6SfunwqGaVkuKDja0bP56aBF3zU1ZVr4a+drlRKnoxZb/Gjgt6y0aARWC1cAv9/l8qIz8AylGZQf9rXERwOgU81w+4GVlRZ/L19m/Gbr9TxOba6x42NE3rns+eLWOco3PE2Nf+j+3/L1k1AegE+5ktk7CxNCi3UATWHjSHfHeCeDeAz4LR82ryAGplj4veCOFcCYM9174j+9OC2mr8xD11ktei2x829Zkmn0ipbGnD0P0v+m0EBMRlhk2Mr6C93MDuYZOunKTgAuV+A+1tQ4jMHvHOM024IM3uyL8ohO4vX/8gWipbZiBIC3OP18WWZjF1YMIJ/sTFldclNdSwUaD1TjC3EwWaRrF7NQuxq/SqK+ejQ9ttsy5eO1+3cGcyftLAewNOxBBEYM4dTnzRg/rE6ABrAW3ie2WX6FtV5krbxB+10Cgwd0p9pqqZeghVo6M5AFPFxRUqjDhxoD3ozMC+oNeuyx7MPdAOTtOIct9VG0wuzbrs0Xnk23Cu0J2jW3l42zPXR4FYC/Yn/J7YpTmrI+FZD9CuFrD17RyL2MerYQdO5gGpzvGmY5KHuLOXME5tYrcg5RmEBoFihP8HFkYco/yBZyOiKBMNDGE0saDweev7kcNyRWonKZdAnOMtrIEk9XQ1MQxxG18FAJI8BtRDcm7fW9XcPC0AQOdd298hpVJQKhWaPjwHnWsrcJSXsUsitMZ60+dQAAVIyfZXThDZ+J3q9y76w6zTlXR+O7CtbiQ6w4IOvB4V0E+/zlFA37mc3xBczZrHJeuhzOwBo7YQ1XW/M2TErt/V/jB81eHfT/aV3w2vM863bWzIAzjQtKgi+BHm3b2fXLSReGR4SOVrclIlrClw9CdQZRAY+SpAB0pNar4FwCqz8xB1Z3e0KI6sPIUH41NZOrbcqJY7/rAPvegj42g9xN3j9+OkCIVOilpcd1mTwP5wezEhs8NIiYVxUhyGR07RWoqbQeH2esHNzUoe3r2ZeDxC07FIVjXVXuSv7DTOitB0AWj/yMLiuNAP1axGqqkS4n+RqihqxKIUjgQ67xT/l2bv/nNtvB66w6i1GIMwEWt2s4G0KzAtOVwgu6Z85t6L7dx4aktmCYIGsMMdH99fUDNQ9JUnugdm1RgXho0urtTAHUe5nhrOb4Xgk/obf3HKDQJ72e4qeYnGj2Ii9ouhkOAkUywkcvHn/6ihB8/j6HQ5a94BrKBed+965Fwe0Cce46jPAkkZyUS1sTlwhNIaAT5Gfx9m7ea2HEfmWhEDUQv1kpKK+sGG6oyYaFO8G+m35N2NqjyVEeCS5HESvM38lEZnVy/d7t9naqBSNMhV4xLv5TP3EkqSyd7s230uR1FtK95qP+d/nto+o7DOnUSM1IA5bPFkFjSLpheOCLtEiVFT4MTa7QCNR7kW8UiHedoYJbH1V8PSB1BN7Tck3xH965pAr80sjakGM8MwxBxSfUT1bz0bPyoaNCtAwoNmj77ZddXr5twXU4DF22O32p5mTflqf4Qpw0EV5bbQ/V6AQY/XudgEWsuLUdsWfbuWtLkT4Bnzx/r26nLONTEJBmSI5zrDIYKWklt1DOFyFJvAVlo9qr9WDnWQSKzJFzII5GaJikEk+BJr0nheeCMBn2ZQSbJ6RoSh4SVugyL9m8ReT2XAsagpmrb1UeTVV+3jlptgNuZdI5yrqzn/Dr1DL6XI5jhbTj/CG7j7lQSp8I0jPwErYv6qYcIBmvjGs0q9Iew=
      encrypted: true
      hash: b4262bf9dd8fcaaaf58e9ef68d4a923c346f2192ad47280d64d4ed2fd94b04e7
  mailgun:
    domainkey:
      ciphertext: IcvgQ2+2uhvaQ5vTmHXkgyYWtrNbMdKziOz2FQlgfuzDYBsGumu92vmpgGnWKnq+lHLdv4eIR6Az4Hxgb2/wgPGCwEeaUmDuoLype2wCHsDlbBdgW3j1w/pgXj+mUtUYpIKv2rMUBuVaq7F81GaxwpNZf3UD18oTvrkpAnYqo9YNz5eZcmg9e9mCQAVqOn9MY1kcCgwPuR6S4n+NmzVvbbMKN51tqDLycXbZI/mTc4EwAOTnYXlsYVjfx4TgOT4p22W/lEKCuPEJHfJlw1KRpHMqWPzyXM9XNRExrRAughPClP8NqPT8HPDgmgIYa6EWmEDdqG5HiaOJmDxSUzjg1Nv29Yv8HPA953ueLBK+c/bsi7OzO0YWoxOVbYDob9wFzpLsuNZNGOoxT7BYrjSYiRJ0Wfcl84eXSMepR0yoVsnVKq4eBKVKmFgh7xJEzfAM8Czi6aaxkRMgks5lEjsdnu2VHS/9PXcuFe1CSlPElXy/F/OZXwmppv4U6DYF8UX0QW5hv5Yk70OiFuZlrQluOm4yRebGQckwOWRH7UH2LnOZRfLlCJE8b9zqm+Y9PwHo0qCI5/Up9OxcmncV/CeeUiU=
      encrypted: true
      hash: db2bf63c2d1f89fd207de36b55d428114dab66d5e784137798ddc002b28f4c18
    dsm:
      ciphertext: RD5i7jUoREEXjmZ/R/IZpagjQuxN7ZRYRGqr9r+CXgqZ1hBeCeRNU8NqFpydSUbWa7/jkXXnZTZuV4Gk3bKdeHPxI6dULd/wmBmu9wdMF+j75rUaVR9x1Z5TTuSkW792F7E=
      encrypted: true
      hash: 3d856eb9a77ce054f2fa9ea632a6d515e57b2ffeb6767c7861fb8c1b253c1bf5
  minio:
    key:
      ciphertext: iJ9j7LmqYDJypNCOgeCZlnO+dK1/aq45bLosayCbtCmTxsgmn/w4HF2SPAM93FRRS1kiYGg=
      encrypted: true
      hash: 5ae0a39b9dc084b59aa32256335bd60eac3107bac9ecc6eb1688d2ff2ec67c87
    secret:
      ciphertext: kuuyuE5wE7loigXTOyUiG+473/HiVQ9oF6SwZ0sepPyTe0a29ZqdFyhdQY8v4fQhRqdJ4olfvlP7R1R/0xyPXc59aPPTtvbRCk2nooYRlzk=
      encrypted: true
      hash: 80a8bd31044087e0fb91b09352caec645fbe877a413952b929be5e7bb6fbb2a7
  putio:
    token:
      ciphertext: foEDv5DnJBCc8pyLEVGcLjzDiU7w2Lzb/S3xv+mldmOFCifkOaKg3o2a48UI8IiEfAmo7jUe+sIF/2dJmC3IB8++KKM=
      encrypted: true
      hash: 185c617da3d73d02902b97048f792efdaa742f1ba44b8175547fdc88189debbb
  tvdb:
    key:
      ciphertext: kitleWBismWyiCCnGAfN2PWCQslwWhIj0JinNUDz5OEe+eycTtix0za1uRoZdxtB5dGGFXaSVl7dd4ejRjUAUw==
      encrypted: true
      hash: 67bc04fea9369cb5b9791b01b7dd21d3615b13d1dc59dd9c4843c7a58d6b2e0e
  wireguard:
    clients:
    - public:
        hash: ef113eb595b64cc0458fbefa1c850a01f15dde616176afcc2fff337b2318323a
        ciphertext: IyXX30Z/4s1Y6hLcwkAZhvjCZDic0yJE3ONUnaW+bTYjqy2O9JWnHu/oX1ZRIglyTY3oAsQDExUMzscIAeIZTtFE5K+NDfN2MxyH/y0uyxe9YFwRGUmOKAj1ABc=
        encrypted: true
      private:
        encrypted: true
        hash: 3c6943a934d97f796ae7f68893f93df5cc0791588503c4eeb492aa1c4dab1555
        ciphertext: HcRm6jMc1seCyHoJskB2Gt4Py0AleH0Ugc68e3yZXvctXPejWxMkOBLq/ZY6nbRXU3hFS5BZ63A7dCmFg7Nc1ewAxRyzzdiGPidJ48T0DHfhxpuiBhQZi8M6mrI=
    - public:
        ciphertext: C+/asgFmkEb59DQlVgdDNWYDpWlvhjWXsUVnuixiR5HRT0tceUtXX2p3H5Yxf0BaSNdNmMd2DG6J/gJMaVNsdpzPYxRhjrBlcSrEbyUK/QLA215oj5eA4d7oMUQ=
        encrypted: true
        hash: 9f96fbde50ed1a5520e0108738ab4532fb86dcce294bfef89cb66a13e1b6df75
      private:
        ciphertext: BX2GOz6dGqb2nATTIBFKzXPNECAUAH1CtkkdWL7Gk0LfG9UNu3Qf8KSAk9EJDPT8ELYh6mgjl1wRsHdudsi5/Z/UoEGLRO0wTI70h3135lwZV3yh50ToLJ2KOoc=
        encrypted: true
        hash: d7fcd653186e47c3bce1600b45459fa208328fa239a5bc4154ac6745b403c01a
    interface: eth0
    key:
      ciphertext: LMx495cguGZfcMsD/Z0s5F2RfYFM80XJAC9dmKzuFLC7Hw8S/zNzu+njIM61L62EclqADy7s+9v1ov1EfoqYVWaihNb7xMK0wptJtqHP3Nm8jLf3IO3Vmr2905c=
      encrypted: true
      hash: d7fcd653186e47c3bce1600b45459fa208328fa239a5bc4154ac6745b403c01a
    port: 1194
vault:
  port: 5570
  version: 1.4.1
