{
 "title": "Overview",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "nodes",
    "query": {
     "query": "label_values(nomad_client_allocated_cpu, instance)"
    }
   },
   {
    "name": "jobs",
    "query": {
     "query": "label_values(nomad_client_allocs_cpu_total_percent{instance=~\"$nodes\"}, task_group)"
    }
   },
   {
    "name": "tasks",
    "query": {
     "query": "label_values(nomad_client_allocs_cpu_total_percent{instance=~\"$nodes\", task_group=~\"$jobs\"}, task)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Network Traffic",
   "type": "timeseries",
   "description": "Basic network info per interface",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "rate(node_network_receive_bytes_total{instance=\"10.42.20.1:9100\",device!~\"(npi|loop|lo|itf|imq).*\"}[$__rate_interval])*8",
     "legendFormat": "rx {{device}}"
    },
    {
     "expr": "rate(node_network_transmit_bytes_total{instance=\"10.42.20.1:9100\",device!~\"(npi|loop|lo|itf|imq).*\"}[$__rate_interval])*-8",
     "legendFormat": "tx {{device}} "
    }
   ]
  },
  {
   "title": "Güaifai",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Clients / UAP",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "unifipoller_device_stations{station_type=\"user\"}",
     "legendFormat": "{{name}} {{station_type}}s"
    },
    {
     "expr": "unifipoller_device_stations{station_type=\"guest\"}",
     "legendFormat": "{{name}} {{station_type}}s"
    }
   ]
  },
  {
   "title": "wifi clients",
   "type": "state-timeline",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "expr": "max by (name) (unifipoller_client_rssi_db{essid!=\"robotitos\"})"
    }
   ]
  },
  {
   "title": "UAP Bandwidth / Wireless Devices",
   "type": "timeseries",
   "description": "Bandwidth usage per wireless devices as reported by the UAPs. Rx is on the negative axis. Does not include amazon devices.",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum by (name) (rate(unifipoller_client_transmit_bytes_total{name!~\".*camera.*|.*cam(era)?$\"}[$__interval]))",
     "legendFormat": "{{name}} {{mac}} Tx"
    },
    {
     "expr": "sum by (name) (rate(unifipoller_client_receive_bytes_total{name!~\".*camera.*|.*cam(era)?$\"}[$__interval])*-1)",
     "legendFormat": "{{name}} {{mac}} Rx"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Nomad Uptime",
   "type": "bargauge",
   "gridPos": { "h": 4, "w": 7, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "dtdhms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "last_over_time(nomad_client_uptime{service=\"nomad\"}[1h])"
    }
   ]
  },
  {
   "title": "Consul server state",
   "type": "state-timeline",
   "gridPos": { "h": 4, "w": 7, "x": 7, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "consul_autopilot_healthy + consul_server_isLeader",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  { "title": "Resource Usage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 31 } },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 32 },
   "targets": [
    {
     "expr": "avg by (instance) (avg_over_time(nomad_client_host_cpu_total[10s]))"
    }
   ]
  },
  {
   "title": "cpu usage by nomad task",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 7, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "avg by (task, task_group, instance) (avg_over_time(nomad_client_allocs_cpu_total_percent{instance=~\"$nodes\", task=~\"$tasks\", task_group=~\"$jobs\", service=\"nomad\"}[15s]))",
     "legendFormat": "{{task}}/{{task_group}} @ {{instance}}"
    }
   ]
  },
  {
   "title": "Network CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 32 },
   "targets": [
    {
     "expr": "100 - (avg by (instance) (rate(node_cpu_seconds_total{mode=\"idle\"}[1m])) * 100)",
     "legendFormat": "{{ instance }}"
    },
    {
     "expr": "avg by (name) (avg_over_time(unifipoller_device_cpu_utilization_ratio[1m]))",
     "legendFormat": "{{ name }}"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 40 },
   "targets": [
    {
     "expr": "(sum by (instance) (nomad_client_host_memory_used{service=\"nomad\"})/ sum by (instance) (nomad_client_host_memory_total{service=\"nomad\"}))*100"
    }
   ]
  },
  {
   "title": "mem usage by nomad task",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 7, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by (task, task_group, instance) (nomad_client_allocs_memory_usage{instance=~\"$nodes\", task=~\"$tasks\", task_group=~\"$jobs\", service=\"nomad\"})",
     "legendFormat": "{{task}}/{{task_group}} @ {{instance}}"
    }
   ]
  }
 ]
}