- name: Get installed version
  shell: nomad --version | head -n 1 | cut -dv -f2
  register: installed_nomad_version
  ignore_errors: yes
  check_mode: no

- name: Install nomad
  when: installed_nomad_version.stdout != config.services.nomad.version
  notify: Restart nomad service
  unarchive:
    src: "https://releases.hashicorp.com/nomad/{{ config.services.nomad.version }}/nomad_{{ config.services.nomad.version }}_darwin_amd64.zip"
    remote_src: yes
    dest: /usr/local/bin

- name: Create the nomad config directory
  become: true
  file:
    path: "{{ nomad_config_dir }}"
    owner: "{{ nomad_user }}"
    group: _nidito
    state: directory
    mode: u=rwx,g=rwx,o=

- name: Create the nomad data directory
  become: true
  file:
    path: "/var/lib/nomad"
    owner: "{{ nomad_user }}"
    group: _nidito
    state: directory
    mode: u=rwx,g=rwx,o=

- name: Install nomad launchd config
  become: yes
  template:
    src: templates/service.plist.j2
    dest: /Library/LaunchDaemons/io.nomad.daemon.plist


