- include: "{{ node.platform }}.yml"

- name: Configure consul
  become: true
  template:
    src: templates/config.hcl.j2
    dest: "{{ node.consul.config }}/config.hcl"
    owner: "{{ node.consul.user }}"
    mode: u=rw,g=r,o=
  notify: restart consul
