- name: Download nomad
  when: needs_install
  become: yes
  get_url:
    url: "https://releases.hashicorp.com/nomad/{{ nomad.version }}/nomad_{{ nomad.version }}_linux_{{ golang_artifact_arch }}.zip"
    dest: /tmp

- name: Install nomad binary
  when: needs_install
  become: yes
  shell: |
    cd /tmp
    7z e nomad_{{ nomad.version }}_linux_{{ golang_artifact_arch }}.zip
    mv -f /tmp/nomad {{ nomad.bin }}
    rm -rf /tmp/nomad_{{ nomad.version }}_linux_{{ golang_artifact_arch }}.zip
  notify:
    - restart service
