- name: Download nomad
  when: needs_install
  become: yes
  get_url:
    url: "https://releases.hashicorp.com/nomad/{{ config.services.nomad.version }}/nomad_{{ config.services.nomad.version }}_linux_{{ golang_artifact_arch }}.zip"
    dest: /tmp

- name: Install nomad binary
  when: needs_install
  become: yes
  shell: |
    cd /tmp
    7z e nomad_{{ config.services.nomad.version }}_linux_{{ golang_artifact_arch }}.zip
    mv -f /tmp/nomad {{ nomad.bin }}
    rm -rf /tmp/nomad_{{ config.services.nomad.version }}_linux_{{ golang_artifact_arch }}.zip
  notify: restart nomad

- name: configure systemd
  include_tasks: _systemd.yml
