- name: Restart coredns systemd service
  when: ansible_pkg_mgr is undefined or ansible_pkg_mgr == "pacman"
  listen: restart coredns
  become: yes
  systemd:
    name: coredns
    state: restarted

- name: Reload systemd daemons
  when: ansible_pkg_mgr is undefined or ansible_pkg_mgr == "pacman"
  listen: reload systemd daemons
  become: yes
  systemd:
    daemon_reload: true
    name: coredns
    enabled: true

- name: Restart coredns launchctl service
  when: ansible_pkg_mgr is not undefined and ansible_pkg_mgr == "homebrew"
  listen: restart coredns
  become: yes
  shell: "launchctl stop io.coredns.daemon 2>/dev/null; launchctl load -w /Library/LaunchDaemons/io.coredns.daemon.plist"
