{
 "title": "Casa",
 "time": { "from": "now-14d", "to": "now" },
 "panels": [
  { "title": "Ambiente", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Temperatura",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "max by (name) (hue_sensor_temperature{})",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  { "title": "Fierros", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 } },
  {
   "title": "internet rx/tx",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "rate(node_network_receive_bytes_total{instance=\"10.42.20.1:9100\",device=\"eth9\"}[1m])*8",
     "legendFormat": "rx"
    },
    {
     "expr": "rate(node_network_transmit_bytes_total{instance=\"10.42.20.1:9100\",device=\"eth9\"}[1m])*-8",
     "legendFormat": "tx"
    }
   ]
  },
  {
   "title": "internet rx/tx",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "increase(node_network_receive_bytes_total{instance=\"10.42.20.1:9100\", device=\"eth9\"}[$__rate_interval])*8",
     "legendFormat": "rx"
    },
    {
     "expr": "increase(node_network_transmit_bytes_total{instance=\"10.42.20.1:9100\", device=\"eth9\"}[$__rate_interval])*8",
     "legendFormat": "tx"
    }
   ]
  },
  {
   "title": "memory usage",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(node_memory_Active_bytes) + sum(node_memory_active_bytes)",
     "legendFormat": "used"
    }
   ]
  }
 ]
}