{
 "title": "Overview",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "nodes",
    "query": {
     "query": "label_values(nomad_client_allocated_cpu, instance)"
    }
   },
   {
    "name": "jobs",
    "query": {
     "query": "label_values(nomad_client_allocs_cpu_total_percent{instance=~\"$nodes\"}, task_group)"
    }
   },
   {
    "name": "tasks",
    "query": {
     "query": "label_values(nomad_client_allocs_cpu_total_percent{instance=~\"$nodes\", task_group=~\"$jobs\"}, task)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Traffic", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Firewall",
   "type": "timeseries",
   "description": "Basic network info per interface",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "rate(node_network_receive_bytes_total{instance=\"10.42.20.1:9100\",device!~\"(npi|loop|lo|itf|imq).*\"}[$__rate_interval])*8",
     "legendFormat": "rx {{device}}"
    },
    {
     "expr": "rate(node_network_transmit_bytes_total{instance=\"10.42.20.1:9100\",device!~\"(npi|loop|lo|itf|imq).*\"}[$__rate_interval])*-8",
     "legendFormat": "tx {{device}} "
    }
   ]
  },
  {
   "title": "switch0",
   "type": "timeseries",
   "description": "Bandwidth usage per wireless devices as reported by the UAPs. Rx is on the negative axis. Does not include amazon devices.",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum by (name) (rate(unifipoller_client_transmit_bytes_total{name!~\".*camera.*|.*cam(era)?$\"}[$__interval]))",
     "legendFormat": "{{name}} {{mac}} Tx"
    },
    {
     "expr": "sum by (name) (rate(unifipoller_client_receive_bytes_total{name!~\".*camera.*|.*cam(era)?$\"}[$__interval])*-1)",
     "legendFormat": "{{name}} {{mac}} Rx"
    }
   ]
  },
  {
   "title": "Güaifai",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Clients / UAP",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
   "targets": [
    {
     "expr": "unifipoller_device_stations{station_type=\"user\"}",
     "legendFormat": "{{name}} {{station_type}}s"
    },
    {
     "expr": "unifipoller_device_stations{station_type=\"guest\"}",
     "legendFormat": "{{name}} {{station_type}}s"
    }
   ]
  },
  {
   "title": "wifi clients",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 19 },
   "targets": [
    {
     "expr": "avg by (name) (unifipoller_client_rssi_db{essid!=\"robotitos\"})"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Consul server state",
   "type": "state-timeline",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "consul_autopilot_healthy + consul_server_isLeader",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "nomad server state",
   "type": "state-timeline",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "(sum(clamp_max(nomad_client_uptime{service=\"nomad\"}, 1)) by (instance) + sum(clamp_max(nomad_nomad_autopilot_healthy{service=\"nomad\"}, 1)) by (instance))\nor\n(sum(clamp_max(nomad_client_uptime{service=\"nomad\"}, 1)) by (instance) unless sum(clamp_max(nomad_nomad_autopilot_healthy{service=\"nomad\"}, 1)) by (instance))\nor\n(sum(clamp_max(nomad_nomad_autopilot_healthy{service=\"nomad\"}, 1)) by (instance) unless sum(clamp_max(nomad_client_uptime{service=\"nomad\"}, 1)) by (instance))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Vault server state",
   "type": "state-timeline",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "vault_core_active + vault_core_unsealed",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Nomad Uptime",
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "dtdhms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "last_over_time(nomad_client_uptime{service=\"nomad\"}[1h])"
    }
   ]
  },
  { "title": "Resource Usage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 38 } },
  {
   "title": "cpu usage by nomad task",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "avg by (task, task_group, instance) (avg_over_time(nomad_client_allocs_cpu_total_percent{instance=~\"$nodes\", task=~\"$tasks\", task_group=~\"$jobs\", service=\"nomad\"}[15s]))",
     "legendFormat": "{{task}}/{{task_group}} @ {{instance}}"
    }
   ]
  },
  {
   "title": "mem usage by nomad task",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by (task, task_group, instance) (nomad_client_allocs_memory_usage{instance=~\"$nodes\", task=~\"$tasks\", task_group=~\"$jobs\", service=\"nomad\"})",
     "legendFormat": "{{task}}/{{task_group}} @ {{instance}}"
    }
   ]
  },
  {
   "title": "op-connect request rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "avg by(instance, path, method) (rate(secret_service_api_http_method_counts[$__rate_interval]))",
     "legendFormat": "{{method}} {{path}} @ {{ instance }}"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 47 },
   "targets": [
    {
     "expr": "100 - (avg by (instance) (rate(node_cpu_seconds_total{mode=\"idle\",job=\"host_metrics\"}[1m])) * 100)"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 47 },
   "targets": [
    {
     "expr": "(sum by (instance) (nomad_client_host_memory_used{service=\"nomad\"})/ sum by (instance) (nomad_client_host_memory_total{service=\"nomad\"}))*100"
    }
   ]
  },
  {
   "title": "Vault request rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "rate(vault_core_handle_request_count[$__rate_interval])",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Network CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 55 },
   "targets": [
    {
     "expr": "100 - (avg by (instance) (rate(node_cpu_seconds_total{mode=\"idle\",job!=\"host_metrics\"}[1m])) * 100)",
     "legendFormat": "{{ instance }}"
    },
    {
     "expr": "avg by (name) (avg_over_time(unifipoller_device_cpu_utilization_ratio[1m]))",
     "legendFormat": "{{ name }}"
    }
   ]
  },
  {
   "title": "Disk Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 55 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "avg by(instance, disk) (nomad_client_host_disk_used_percent{service=\"nomad\", disk!~\".*(devfs|disk1s|disk3s[^16]s?|auto_home).*\", instance=~\"$nodes\"})",
     "legendFormat": "{{instance}}:{{disk}}"
    }
   ]
  },
  {
   "title": "Rack Temp",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 55 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "max by (name) (hue_sensor_temperature{name=\"Biblioteca rack\"})",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "CPU Temp",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 63 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "max by (instance, chip) (node_hwmon_temp_celsius{chip!=\"platform_applesmc_768\"})",
     "legendFormat": "{{instance}}"
    }
   ]
  }
 ]
}