- name: Install consul
  become: yes
  pacman:
    name: consul
    state: present

- name: Get installed version
  shell: consul --version | head -n 1 | cut -dv -f2
  register: installed_consul_version
  check_mode: no

- set_fact:
    needs_install: "{{ installed_consul_version.stdout != nidito.consul.version}}"
  check_mode: no

- name: Download a more recent consul version
  when: needs_install
  become: yes
  unarchive:
    remote_src: yes
    src: "https://releases.hashicorp.com/consul/{{ nidito.consul.version }}/consul_{{ nidito.consul.version }}_linux_armhfv6.zip"
    dest: /usr/bin

- name: Enable consul daemon
  become: yes
  systemd:
    name: consul
    enabled: yes
