- name: Add the consul user
  become: true
  user:
    name: "{{ consul.user }}"
    groups: "{{ user.group }}"
    create_home: no
    shell: /usr/bin/false

- name: Install consul
  when: needs_install
  become: yes
  unarchive:
    remote_src: yes
    src: "https://releases.hashicorp.com/consul/{{ consul.version }}/consul_{{ consul.version }}_linux_{{ golang_artifact_arch }}.zip"
    dest: "{{ consul.bin | dirname }}"
  notify:
    - restart service
