- name: Add the consul user
  become: true
  user:
    name: "{{ consul.user }}"
    create_home: no
    shell: /usr/bin/false

- name: Install consul
  when: needs_install
  become: yes
  unarchive:
    remote_src: yes
    src: "https://releases.hashicorp.com/consul/{{ config.services.consul.version }}/consul_{{ config.services.consul.version }}_linux_{{ golang_artifact_arch }}.zip"
    dest: "{{ consul.bin | dirname }}"

- name: configure systemd
  include_tasks: _systemd.yml
