- name: Add the consul user
  become: true
  user:
    name: "{{ consul_user }}"
    create_home: no
    shell: /usr/bin/false
    append: yes

- name: Get installed version
  shell: consul --version | head -n 1 | cut -dv -f2
  register: installed_consul_version
  check_mode: no

- set_fact:
    needs_install: "{{ installed_consul_version.stdout != config.services.consul.version}}"
  check_mode: no

- set_fact:
    golang_artifact_arch: "arm"
  when: node.hardware.arch == 'arm32'

- set_fact:
    golang_artifact_arch: "arm64"
  when: node.hardware.arch == 'arm64'

- set_fact:
    golang_artifact_arch: "amd64"
  when: node.hardware.arch == 'x86_64'

- name: Download a more recent consul version
  when: needs_install
  become: yes
  unarchive:
    remote_src: yes
    src: "https://releases.hashicorp.com/consul/{{ config.services.consul.version }}/consul_{{ config.services.consul.version }}_linux_{{ golang_artifact_arch }}.zip"
    dest: /usr/bin

- name: Install systemd service
  become: yes
  copy:
    src: files/consul.service
    dest: /usr/lib/systemd/system/

- name: Enable consul daemon
  become: yes
  systemd:
    name: consul
    enabled: yes
