- name: Get installed version
  shell: /usr/syno/bin/synopkg version consul
  register: installed_version
  check_mode: no
  ignore_errors: yes

- set_fact:
    needs_install: "{{ installed_version.stdout != nidito.consul.version }}"
    # needs_install: false
    consul_zip: "consul_{{ nidito.consul.version }}_linux_amd64.zip"

- name: Get consul SPK
  when: needs_install
  git:
    name: https://github.com/numkem/consul-spk.git
    dest: /tmp/consul-spk
    update: no

- name: Copy consul patch
  when: needs_install
  template:
    src: "templates/consul-spk.patch"
    dest: /tmp/consul.patch
    mode: u=rw,g=r,o=
  
- name: Apply consul patch
  when: needs_install
  shell: |
    cd /tmp/consul-spk
    git reset --hard
    git apply ../consul.patch
    rm -rf ../consul.patch

- name: Get consul binary
  when: needs_install
  get_url:
    url: "https://releases.hashicorp.com/consul/{{ nidito.consul.version }}/{{ consul_zip }}"
    dest: /tmp/

- name: Unzip binary
  when: needs_install
  shell: |
    cd /tmp
    7z e {{ consul_zip }}
    mkdir -p /tmp/consul-spk/1_create_package/consul
    mv -f /tmp/consul /tmp/consul-spk/1_create_package/consul/
    rm -rf /tmp/{{ consul_zip }}

- name: Create SPK
  when: needs_install
  shell: cd /tmp/consul-spk; sh ./create_spk.sh

- name: Install SPK
  when: needs_install
  become: true
  shell: /usr/syno/bin/synopkg install /tmp/consul-spk/consul.spk

- name: Create the consul config directory
  when: needs_install
  become: true
  file:
    path: "{{ node.consul.config }}"
    owner: "{{ node.consul.user }}"
    state: directory
    mode: u=rwx,g=rwx,o=
