- name: Get installed version
  shell: /usr/syno/bin/synopkg version consul
  register: installed_version
  check_mode: no
  ignore_errors: yes

- set_fact:
    needs_install: "{{ installed_version.stdout != config.services.consul.version }}"
    # needs_install: false
    consul_zip: "consul_{{ config.services.consul.version }}_linux_amd64.zip"

- name: Get consul SPK
  when: needs_install
  git:
    name: https://github.com/numkem/consul-spk.git
    dest: /tmp/consul-spk
    update: no

- name: patch spk
  lineinfile:
    path: "/tmp/consul-spk/{{ item.path }}"
    state: present
    regexp: "{{ item.regex }}"
    line: "{{ item.line }}"
    backrefs: yes
  with_items:
    - path: 1_create_package/ui/config
      regex: '^(\s+)"port":"[\d+]"(,?)'
      line: '\g<1>"port": "{{ config.services.consul.ports.http }}"\g<2>'
    - path: 2_create_project/INFO
      regex: '^version="[\d.]+"'
      line: 'version="{{ config.services.consul.version }}"'
    - path: 2_create_project/INFO
      regex: '^adminport="?[\d.]+"?'
      line: 'adminport={{ config.services.consul.ports.http }}'
    - path: 2_create_project/scripts/consul.sc
      regex: '^dst.ports=.+'
      line: 'dst.ports="{{ config.services.consul.ports.http }}/tcp {{ config.services.consul.ports.serf_lan }},{{ config.services.consul.ports.serf_wan }}/tcp,udp {{ config.services.consul.ports.dns }}/udp"'

- name: Get consul binary
  when: needs_install
  get_url:
    url: "https://releases.hashicorp.com/consul/{{ config.services.consul.version }}/{{ consul_zip }}"
    dest: /tmp/

- name: Unzip binary
  when: needs_install
  shell: |
    cd /tmp
    7z e {{ consul_zip }}
    mkdir -p /tmp/consul-spk/1_create_package/consul
    mv -f /tmp/consul /tmp/consul-spk/1_create_package/consul/
    rm -rf /tmp/{{ consul_zip }}

- name: Create SPK
  when: needs_install
  shell: cd /tmp/consul-spk; sh ./create_spk.sh

- name: Install SPK
  when: needs_install
  become: true
  shell: /usr/syno/bin/synopkg install /tmp/consul-spk/consul.spk

- name: Create the consul config directory
  when: needs_install
  become: true
  file:
    path: "{{ consul_config_dir }}"
    owner: "{{ consul_user }}"
    state: directory
    mode: u=rwx,g=rwx,o=
