primary: true
dns:
  authority: coredns
  leaders: tepetl
  # zone for stuff
  zone: nidi.to
peering:
  address: 10.42.31.1/24
  endpoint: !!secret
  key:
    public: !!secret
    private: !!secret
  peers:
    rob:
      public_key: !!secret
      allowed_ips:
        - 10.42.31.42/32
    bernal:
      dc: qro0
subnet: 10.42.0.0/16
vault:
  nomad_token: !!secret
  unseal_key: !!secret
  root_token: !!secret
