dns:
  authority: external
  leaders: bedstuy
  zone: rob.mx
peering:
  address: 10.42.31.3/32
  endpoint: !!secret
  peers:
    anahuac:
      dc: casa
      resolve_dns: true
  private_key: !!secret
  public_key: !!secret
primary: false
subnet: 10.100.0.0/20
vault:
  nomad_token: !!secret
  unseal_key: !!secret
  root_token: !!secret
nomad:
  # created with
  # nomad acl token create -type="management" -global=true -name="nyc1 Replication Token"
  replication:
    accessor: !!secret
    secret: !!secret
