dns:
  authority: external
  leaders: bernal
  zone: rob.mx
peering:
  address: 10.142.21.1/24
  endpoint: !!secret
  peers:
    anahuac:
      dc: casa
      resolve_dns: true
  key:
    private: !!secret
    public: !!secret
primary: false
subnet: 10.142.20.0/24
vault:
  nomad_token: !!secret
  unseal_key: !!secret
  root_token: !!secret
nomad:
  replication:
    accessor: !!secret
    secret: !!secret
