# see `milpa help docs command spec` for all the options
summary: Diffs a config file
description: |
  used in .gitattributes as

  ```
  path/to/file.yaml diff="nidito-config"
  # and .git/config
  [diff "nidito-config"]
  textconv = milpa nidito config secrets filter diff
  binary = true
  ```

  https://git-scm.com/docs/git#Documentation/git.txt-codeGITEXTERNALDIFFcode
arguments:
  - name: path
    description: idk
    required: true
  - name: old-file
    description: old version of file
  - name: old-sha
    description: old file sha
  - name: old-mode
    description: old file mode
  - name: new-file
    description: new version of file
  - name: new-sha
    description: new file sha
  - name: new-mode
    description: new file mode
