consul:
  user: consul
  config: /etc/consul.d
  bin: /usr/bin/consul
  data: /var/lib/consul
  logs: # journald
  version: 1.18.1
  source: https://github.com/hashicorp/consul
  check: hc-releases
  systemd:
    wants:
    after:
coredns:
  user: coredns
  group: users
  version: v0.3.0
  source: https://github.com/unRob/coredns-consul
  check: github-releases
  config: /etc/coredns.d
  bin: /usr/bin/coredns
  systemd:
    after: network-online.target
    wants: consul.target
docker:
  engine: 20.10
  cni_plugins: 1.2.0
user:
  group: nidito
node_exporter:
  bin: /usr/local/bin/node_exporter
  address: "{{ node.address }}"
  logs: # journald
  version: 1.7.0
  source: https://github.com/prometheus/node_exporter
  check: github-releases
  comparison: suffix
  systemd:
    wants:
    after:
nomad:
  user: root
  group: root
  bin: /usr/bin/nomad
  config: /etc/nomad.d
  data: /var/lib/nomad
  client_data: /var/lib/nomad/client
  logs: # journald
  version: 1.7.6
  source: https://github.com/hashicorp/nomad
  check: hc-releases
  systemd:
    wants:
    after:
vault:
  config: /etc/vault.d
  bin: /usr/bin/vault
  user: vault
  logs: # journald
  version: 1.16.0
  source: https://github.com/hashicorp/vault
  check: hc-releases
  systemd:
    wants:
    after:
joao:
  version: v0.0.0+alpha.10
  src: "https://cdn.rob.mx/tools/joao/"
  source: https://git.rob.mx/nidito/joao
  check: gitea-tags
systemd:
  prefix: /usr/lib
