consul:
  user: consul
  config: /etc/consul.d
  bin: /usr/bin/consul
  data: /var/lib/consul
  logs: # journald
  systemd:
    wants:
    after:
coredns:
  user: coredns
  group: users
  plugin: v0.1.2
  config: /etc/coredns.d
  bin: /usr/bin/coredns
docker:
  engine: 20.10
  cni_plugins: 1.2.0
user:
  group: nidito
node_exporter:
  bin: /usr/local/bin/node_exporter
  address: "{{ node.address }}"
  logs: # journald
  version: 1.6.1
  systemd:
    wants:
    after:
nomad:
  user: root
  group: root
  bin: /usr/bin/nomad
  config: /etc/nomad.d
  data: /var/lib/nomad
  logs: # journald
  systemd:
    wants:
    after:
vault:
  config: /etc/vault.d
  bin: /usr/bin/vault
  user: vault
  logs: # journald
  systemd:
    wants:
    after:
joao:
  version: v0.0.0+alpha.7
  src: "https://cdn.rob.mx/tools/joao/"
