- include_vars: "{{ node.hardware.os }}.yml"

- include_tasks: "{{ node.hardware.os }}.yml"

- name: Create config directory
  become: true
  file:
    owner: "{{ vault_user }}"
    path: "{{ vault_config_dir }}/tls"
    state: directory
    recurse: yes

- name: Install TLS certs
  become: true
  no_log: true
  copy:
    content: "{{ item.content }}"
    dest: "{{ vault_config_dir }}/tls/{{ item.name }}"
    owner: "{{ vault_user }}"
    mode: u=rw,g=,o=
  with_items:
    - name: ca.pem
      content: "{{ config.services.ca.cert }}"
    - name: key.pem
      content: "{{ node.tls.key }}"
    - name: cert.pem
      content: "{{ node.tls.vault }}"
  notify: restart vault

- name: Configure vault
  become: true
  template:
    src: templates/config.hcl.j2
    dest: "{{ vault_config_dir }}/config.hcl"
    owner: "{{ vault_user }}"
    mode: u=rw,g=r,o=
  notify: restart vault
