- name: Install systemd service
  become: yes
  template:
    src: templates/node-exporter.service.j2
    dest: /usr/lib/systemd/system/node-exporter.service
  notify:
    - reload systemd daemons
    - restart node_exporter

- name: Enable node_exporter daemon
  become: yes
  systemd:
    name: node-exporter
    daemon_reload: yes
    enabled: yes
  notify: restart node_exporter
