- include_role:
    name: _service
  vars:
    service_name: node-exporter
    systemd_template: templates/node-exporter.service.j2

- name: Download node_exporter
  when: needs_install
  become: true
  unarchive:
    remote_src: yes
    src: "{{ node_exporter.source }}/releases/download/v{{node_exporter.version}}/node_exporter-{{node_exporter.version}}.linux-{{ golang_artifact_arch }}.tar.gz"
    dest: "/tmp/"
  notify:
    - restart service

- name: Install node_exporter
  when: needs_install
  become: true
  shell: |
    mv /tmp/node_exporter-{{node_exporter.version}}.linux-{{ golang_artifact_arch }}/node_exporter {{ node_exporter.bin }}
  notify:
    - restart service
