- name: Get installed version
  become: true
  shell: |
    /config/node_exporter/node_exporter --version | awk '/^node_exporter/ {print $3}' -version
  register: node_exporter_installed_version
  check_mode: no
  ignore_errors: yes

- set_fact:
    needs_install: "{{ node_exporter_installed_version.stdout != node_exporter_version }}"

- name: Create the node_exporter directory
  become: true
  file:
    path: /config/node_exporter
    state: directory
    mode: u=rwx,g=rwx,o=

- name: Download node_exporter
  when: needs_install
  become: true
  unarchive:
    remote_src: yes
    src: "https://github.com/prometheus/node_exporter/releases/download/v{{node_exporter_version}}/node_exporter-{{node_exporter_version}}.linux-mips64.tar.gz"
    dest: /tmp/node_exporter

- name: Install node_exporter
  when: needs_install
  become: true
  shell: |
    mv /tmp/node_exporter/node_exporter /config/node_exporter/node_exporter

- name: Install systemd service
  become: yes
  template:
    src: templates/node_exporter.service.j2
    dest: /usr/lib/systemd/system/node_exporter.service

- name: Enable systemd service
  become: yes
  systemd:
    name: node_exporter
    enabled: yes

- name: Create the node_exporter firstboot directory
  become: true
  file:
    path: "/config/scripts/firstboot.d"
    state: directory
    owner: root
    group: vyattacfg
    mode: u=rwx,g=rwx,o=

- name: Install edgerouter firstboot.d script
  become: true
  copy:
    src: files/post-config.sh
    mode: u=rwx,g=rwx,o=rx
    dest: /config/scripts/firstboot.d/node_exporter.sh

- name: Run firstboot script
  when: needs_install
  become: true
  shell: /config/scripts/firstboot.d/node_exporter.sh
