ca:
  cert:
    ciphertext: tvnQriPc5r7uJZPXae++Jt2tWtN+WsDmv3e7Z9jbdjyso5+yc5avBsUGwlRf+nXACRt3aEzkwaqMIfZlD3TMvl2+LsU0eXotVXMaEuNawv1TmI4ruya96EUTHvbQDwALQfmM4xIH5UNKSJ2xecLetmBicsngkn8+gfjCLxyvsTcSODzQeAJ1U1NMMHZnyGqpkH2lXqXx90wqfnXHSGcNk64B2B/mD8QkqJ1ecOceZaTAJMtfau+I+30LJWK3ch1pwgEBS7ISrks8LPF7UXX9XN+9CWN26hRtWHuR2iWLKlIydjauD8ecrShpgYLFuW1Fgcm3/+juiWM0l17RuXTWzpUylYq67my229VMlwS0pwaWWW6+yvBxAYH3HlT33yedvSfTdtVZjOQ+7vDgIXJT7BzcRJHUfmAVEVJMLnUJRkkNoFspPqZtMmJG5jURjGCFl6tbwQkig98OzsCcY2IxqRFqeJZyzjxu3Y0qBtIFOyFmcPydt3iegSFH7z7GulyNSDoASN7ac5wuKYHMZ72Wuz5QgquowQ80bc7br6N0SMrE9y6+AeenHAJc96f6g2+RP3vsECIeDIZFQRlH+slhaiV2d/vva1BL/1T5bC4qTE0caSNlMBl8hvMfTsq3E9Yt77KT0AJ0y+ey93hY6rr2++kLbWxFshINV8VfzHscc+sRI/01GqysYhDKFfV4HOMIuderKUF6ocZMb4+IW/NyOc52/jPoseNErv67yks9DiN1S/GZLfhiSrD/SC73Z6mt41IjL9bZveWVvG/Zqkgn6WgG7wf0Wh2HhOmEkgyxezicVXsfGfBLuFjBLtT7FsScOHOfsKF8erfRjve03SyXhPdj5PL9
    encrypted: true
    hash: 427b41e6d99cedc2ff8d5dd1695b9b834df949e3e2db039e11ab39a5bd0357d3
  key:
    ciphertext: 8CizGLf+dsy0rfeblge2BeXZWmvfNbr5rZOd4HeheKPnKGqXhyVKyXJdIYYfCi1ML1Hgm+Xu1tBlVNFFkEnK8wBCjFJeHa/pfJp0DxdzUXdAQkN5FyNYRcbwPSYkxIb73WQHNsdIszkcCbaKyacQ0o5UhusMlxyhnb1aWyzvjyD2F3qndgv0EnmfSSykGnNYfqOKoR3lf9Nx2mM/6wrnthtg6xMpLDwwfvWH6knCg0HcMcrpzM3CnwrJlctgTKEyrnhuyHbXmTw6QnLUu4TE3EgwzOg3RdnXqg+omIZGkBYy5fZ8eNI/YEYy9QCJ6xVxHiwqFj2nz7Pe1CAqhwsX0krMz1DFpfxQTk1o1EEaR0hRYmuXzg==
    encrypted: true
    hash: 03760d191bc1dd717bcd0d0419c74a60382a91c485a4e8371a5575e89bdc4f95
consul:
  encryption_key:
    ciphertext: utp3DmeQIpL6nB/6MBBekfDFvzd2tEFO/h002fSwzv5gkY8NVzCs2ANRoUBgLSnUMxaRuRcde/7Qj0uWCozMabcuooNMNE0KRIo4NZg/0LLTNIVad71vJ0dFyNs=
    encrypted: true
    hash: ab19fdadeee3cc7e14aff31d312643125003c7cecddd907d4cd716261cd14042
  ports:
    dns: 5553
    http: 5555
    https: 5554
    serf_lan: 5551
    serf_wan: 5552
    server: 5550
  version: 1.10.2
crypto:
  key: nX447KScZXogkbfsFb755uhcwJULlGWwMFyO2Kikaztt2pzXawUCTgf5QHafd0HQ2s1Jh0hVKZgy13X33E95zwswVEc8mqpsrGPnCoh69V9+WlZRebonGR3fEds=
  provider: password
dns:
  consul_token:
    ciphertext: aKf6UAJ5w3fsLq99cqvIb7TaAnZ1+MdyQ2GpkTyf/zUQHkLJdtI27BZnAliqT4ndnuYtoHG1+7KOWhmpcelxGgyKyJ/iXiqFdLNwmALO5PB4qdrb
    encrypted: true
    hash: 77dd385bcbfe1964118b51951124c2fe66ee3dbceba0da40a712ce423b259b87
  external:
    # when resolving non ${dns.zone} queries, forward to
    forwarders:
    - 1.1.1.1
    - 8.8.8.8
    # our domain is a registered TLD whose NS point to:
    nameserver: ns1.digitalocean.com
    provider:
      name: digitalocean
      token:
        ciphertext: zOmnwZv3HYGhn7kVhFD6IBy0tmE8xdb+bN/6Xria+HHqD3fnQ8L+GIfv6lsV+MYV9kKaCfCRTRUUC6x4BzOB+tDPg1BtG/lFMTSHpm/Q46IX8fhQ8jhcZSbq3UxXfMLDxePJev3sOEp0LjwlUKSdEA==
        encrypted: true
        hash: afe6d35ae8fbc96087e14c6c4afd1dede78c68013a158a87186a2b466a71cd62
  # the fully qualified domain name for my nidito
  # all services will be a subdomain of this domain
  zone: nidi.to
honeycomb:
  api_key:
    ciphertext: V57D7CLQgcB4KrZvkeSEusPDJpGrvyVZGyN3HIuIKFY0IspEJpzYwtQmv114dOdZE9E7xzhqrfUfhUeiwEqks/WWmZOKVnhtuB37O+L4w1g=
    encrypted: true
    hash: 571830c89faed59877fa81da105ee48e1c5817354d3d735bc62fe9eae2028a39
letsencrypt:
  email: nidito@un.rob.mx
  private_key:
    ciphertext: tFeKles89CUqPT/SRHB2oeV5PKz2nLzUrDZEFBy5kYn30z6k6qm0yRlznT4Fmeq77MR2ep/jv4hoQ+bh9Gu4sPnrLrmAz8piod/1ziMW8WONhjEl6J1bpirs2qmyDNaX+9ZzIA6uuHfP5h82wy2pd8hQUwewFEst3Lld3pzA3A6+oSkAoxLX/j8Uu3/ehIIr4ixMQRkmUHMjZZ11CcU2cXZyv/KEnPp6dRqYdUBQoGN5Z1e21IQ8Yfvgvh0gYeLtb39WJMhrT4Xd7j/8OEWa4yezuKYcJd3wx7IiZLP2so015eUZkWq0zqWNnDDSqO+QH9G6oGYv9/+BeJItXslG6mwm9j8ZBpgMrvPFFAjBqz67XLD9SQCuM5JD149QGgHaIHpn76Je65o68q6LuKgGvWftW8g79BmviSZABuzg/BAF3JkjnVufWoUAvggmO4+rQxnTq83N2T0pdeDOJSrJj4u2ai/meN/k2fPFHfxrLNdKHnCv7lonrZbpGBMZxKgDTIbNlw56Ah+9BWCzX0hllsDTCQ3cGFXRUiEosa/hLWbFBLr+Q/cuWZBsgbxOVwocYQASDgDjNIpQxr/OtEMjN65k9rbCWBnM7CcxDJA3yHFU+B0WWvKwmxzooCZu+87lQMRrZQX9QaeTRVHipI69fyw6vpdy4Ib+dm5jxV335s4cUO9/ZBbyU2tSrbRhllLWqiUvu1IY6Ia2UbpslKvYiYZYqnGFQhJb8NTU7EULXc56iqi76wOMGYA2+BR2SwHahYfocO/3K9Bj4R9s7xxFQbDCNUPFEVG8T5+nelPlcNeJ46HUD3rW7/oSLY0uO6WcWLzAmZ1DCA4KX0L32Yc1paQXnSEuN2MM7KDSpJD/O9FZ1ieB5ariHCwviLnNDk9wCQWJMagff2em5WJZnwtLcwG0j9tcDffR9wXPODF68YP3fPSNxAHII1tuF5IJ5ynGPUfkPzzguY1gjFOnIejl/1XlFHC+ULRwfo99g5ua4T9XjpY9OHGeiuvzQ6zJFtpCtv9wkUN7JZCPnRNPmwsMMJjZJBYU0aiEPJoXW0+FFDBhbQXjbbvNafr5Lbfj8x6ViB8qEuCJemAxJIkNky4hulLs/njVoqBv2bIkuPghD3L0kPY4T+WA7S4fbW21egdjD7ZcUIve5oZhPBZYo/XrfeSYzzF7GxxnN09nnNJamHlfCUhguL4R3abtZRI3PokoH69h/NkeiAqACzlaG8CxW90bMVEBr4tbTNVTUnZhvWHm703WHdp+P6c64cvagXrdANQ91rG0vRZhP9/IlocKv7bZ3duljW3536vW9Pl3YUzAW5IVTa1rzTgdqnEY6+ZDlgCIPhLaL5Muc4M+BgadgArHcCUwMHmHJgmNA5570w8EcEqnlVGdBD39mkjpVUbKonPWUMb5wg4xj84Jhs0eWOciy8blaVEtwYzT831ChnDQKTeNJirXs+xzog5+EyuuYlSoPH49RdXqTgVZXCrl/D50jK84uyE1VbAO/rj35XQGj1Eiw36uL5NHWtBGa8ozV1Hrs6MU/fMIa5R72vNsGm7ISfXpSS0eJiEqYaawUWbeYPwWLd3DYgIQxjjAcsgRi70SFIRIG9n9ibakRBYcDg80sIgRJL7bPCTbJwxSsyFnj1050KfEp9eSErVxKxkZYeHdMiSjdNO1/Ls0b0Dt0szUa5p9FEIlDmWbZwWvfQnOTlJdMJOH5SBE1OP/IPGpJO9vjkEG2oqiL7enEzgUKLex5qDfaJFdLnPq1md7WjeTxdyuRUIe/k20qbjge3fOYM9uBSwyHIs5YvsHwle04Md2kxkuVWBV0VkLgKrd+pns/uc0aS1h844ZpOWLREayr4Hf3vtHrwJblhOM10gZssUIBDTIVP6IRv9JB21QxE0OBJ+toVyExCnbzjw46WtGj0iqBkAAQrCmA9WL+axHvZJqDxHdamOMavKA3aYIdD2lqJTnUR+BYPhv1eWj9D2XmUi4HuwCG7sofpw2XfWqv0uReq69Daf9TzgJdZKsTXabccz9x3THJGc6JUknIGAO8sSKKwao+XmlsQR+SYkGIFQLG+P7N+z6aISz2zvRu/xSuFpmRQ0vLy8YO8XlcE0i9xu2Ixm1DuFqzP3HxORtJCyO4Z5EMZW1SdGcRajschUcrJk2orgSSnAiVXEBtiZMnvCUJNHmGrrOhvZUQ9KEGblpFrtD6uG2AjAICVBrGnLysixHiBxLMSr+N342U5YbHecu+211w+qP3VtmzYKReDnEW1Rg8Bb/Du+0UttE0QYhsSAvAvHM2toPtUGxJJM=
    encrypted: true
    hash: 3936a233e868177f940b7d9d6718a60b8d90977e8919cf43c61064217a89abdf
mailgun:
  domainkey:
    ciphertext: IcvgQ2+2uhvaQ5vTmHXkgyYWtrNbMdKziOz2FQlgfuzDYBsGumu92vmpgGnWKnq+lHLdv4eIR6Az4Hxgb2/wgPGCwEeaUmDuoLype2wCHsDlbBdgW3j1w/pgXj+mUtUYpIKv2rMUBuVaq7F81GaxwpNZf3UD18oTvrkpAnYqo9YNz5eZcmg9e9mCQAVqOn9MY1kcCgwPuR6S4n+NmzVvbbMKN51tqDLycXbZI/mTc4EwAOTnYXlsYVjfx4TgOT4p22W/lEKCuPEJHfJlw1KRpHMqWPzyXM9XNRExrRAughPClP8NqPT8HPDgmgIYa6EWmEDdqG5HiaOJmDxSUzjg1Nv29Yv8HPA953ueLBK+c/bsi7OzO0YWoxOVbYDob9wFzpLsuNZNGOoxT7BYrjSYiRJ0Wfcl84eXSMepR0yoVsnVKq4eBKVKmFgh7xJEzfAM8Czi6aaxkRMgks5lEjsdnu2VHS/9PXcuFe1CSlPElXy/F/OZXwmppv4U6DYF8UX0QW5hv5Yk70OiFuZlrQluOm4yRebGQckwOWRH7UH2LnOZRfLlCJE8b9zqm+Y9PwHo0qCI5/Up9OxcmncV/CeeUiU=
    encrypted: true
    hash: db2bf63c2d1f89fd207de36b55d428114dab66d5e784137798ddc002b28f4c18
  dsm:
    ciphertext: RD5i7jUoREEXjmZ/R/IZpagjQuxN7ZRYRGqr9r+CXgqZ1hBeCeRNU8NqFpydSUbWa7/jkXXnZTZuV4Gk3bKdeHPxI6dULd/wmBmu9wdMF+j75rUaVR9x1Z5TTuSkW792F7E=
    encrypted: true
    hash: 3d856eb9a77ce054f2fa9ea632a6d515e57b2ffeb6767c7861fb8c1b253c1bf5
minio:
  key:
    ciphertext: iJ9j7LmqYDJypNCOgeCZlnO+dK1/aq45bLosayCbtCmTxsgmn/w4HF2SPAM93FRRS1kiYGg=
    encrypted: true
    hash: 5ae0a39b9dc084b59aa32256335bd60eac3107bac9ecc6eb1688d2ff2ec67c87
  secret:
    ciphertext: kuuyuE5wE7loigXTOyUiG+473/HiVQ9oF6SwZ0sepPyTe0a29ZqdFyhdQY8v4fQhRqdJ4olfvlP7R1R/0xyPXc59aPPTtvbRCk2nooYRlzk=
    encrypted: true
    hash: 80a8bd31044087e0fb91b09352caec645fbe877a413952b929be5e7bb6fbb2a7
nomad:
  consul_token:
    ciphertext: EXVBiVV7oKjCj4cA86SYXKhMdKY7wmMmdkJCeA3ADaAM7XSK08n4ddo2dQJzLxy1aucKa9I8pvl8vKZIqzOjNn8YxadYj9Cx57ig/jmm+hhxOlH+
    encrypted: true
    hash: 4559a891dc9d90a97fce204fd9303a8ee1da65d97c0e5400f7a00bf1c1a0a8d8
  encryption_key: ""
  ports:
    http: 5560
    rpc: 5561
    serf: 5562
  recover_cluster: false
  tokenwhoknows:
    ciphertext: nuN46GN5LVclEgnZ2kgbtSODIQPXofJzZj7Ld1MNXlZT2BBtieqBG9nZcmog14qgNE5uIx30UX9iW1hLtPDtDSMw5aMR3pL3HCk=
    encrypted: true
    hash: 2881b185e83eff77ee409bc08a46845f10c5aae703ef994a6b669b25be5e98ef
  version: 1.1.4
vault:
  consul_token:
    ciphertext: QluEG1esvPsyip6KbZNIoLhfMIEmfEJUkBUZZk3LN1u7WvTIJ+oxZs/KtaWtBeqDGAabh253OpEpN+sCXkkGMdi6jJVmI5BX9D2Bk/vjbM8SOuZu
    encrypted: true
    hash: 6813750aa750e6f0ae6a5c0cde1fa1cb118ef1847c392f764f8bf27f25334886
  port: 5570
  version: 1.6.3
wireguard:
  port: 1194
