- include: "{{ node.platform }}.yml"

- name: Recover cluster
  become: true
  notify: Restart nomad service
  when: nidito.nomad.recover_cluster
  template:
    src: templates/peers.json.j2
    dest: "/var/lib/nomad/server/raft/peers.json"
    owner: "{{ node.nomad.user }}"

- name: Configure nomad
  become: true
  template:
    src: templates/config.hcl.j2
    dest: "{{ node.nomad.config }}/config.hcl"
    owner: "{{ node.nomad.user }}"
    mode: u=rw,g=r,o=
  notify: restart nomad
