#!/usr/bin/env bash

echo "Content-type: text/plain; charset=UTF-8; version=0.0.5"
echo ""
# {{ with secret (printf "cfg/svc/tree/%s:prom-hue-exporter" (env "meta.dns_zone")) }}
HUE_BRIDGE_NOMAD="{{ .Data.bridge }}"
HUE_BRIDGE=${HUE_BRIDGE:-$HUE_BRIDGE_NOMAD}
HUE_KEY_NOMAD="{{ .Data.key }}"
HUE_KEY=${HUE_KEY:-$HUE_KEY_NOMAD}
# {{ end }}
curl --max-time 5 --silent --fail-with-body --show-error "http://$HUE_BRIDGE/api/$HUE_KEY/sensors" |
  jq -r '
  to_entries |
  map(.value + {id: .key, mac:(""+.value.uniqueid | split("-") | first) }) |
  group_by(.mac) |
  values |
  map({
    key: (map(select(.name | startswith("Hue") | not)) | first | .name // "Unknown"),
    value: (. | reduce .[] as $item ({}; .[$item.type] = $item ))
  }) |
  map(
    select(.value.ZLLTemperature.state.temperature // false) |
    {
      key: .key,
      value: (.value.ZLLTemperature.state.temperature/100)
    }
  ) |
  sort_by(.value) |
  map("hue_sensor_temperature{name=\"\(.key)\"} \(.value)")[]'
