# https://github.com/ansible/ansible/issues/75832
- name: fix /usr/bin/capsh permissions
  become: true
  file:
    path: /usr/bin/capsh
    mode: 0755

- name: Install boot script
  become: true
  copy:
    src: files/sigh-synology.sh
    dest: /usr/local/etc/rc.d/nidito.sh
    mode: u=rwx,g=r,o=r
