# https://garagehq.deuxfleurs.fr/documentation/reference-manual/configuration/
{{- $dc := env "node.region" }}
{{- $zone := env "meta.dns_zone" }}
metadata_dir = "/storage/metadata"
data_dir = "/storage/data"

db_engine = "lmdb"

replication_factor = 3
consistency_mode = "consistent"

compression_level = 1
{{ with secret (printf "cfg/svc/tree/%s:garage" $zone) }}
rpc_secret = "{{ .Data.secret }}"
rpc_bind_addr = "[::]:{{ .Data.ports.rpc }}"
rpc_public_addr = "{{ env "NOMAD_ADDR_rpc" }}"
{{ end }}



[consul_discovery]
api = "agent"
consul_http_addr = "{{ env "CONSUL_HTTP_ADDR" }}"
{{ with secret "consul-acl/creds/service-garage" -}}
token = "{{ .Data.token }}"
{{- end }}
service_name = "garage"
ca_cert = "/secrets/tls/ca.pem"
tls_skip_verify = false
tags = ["nidito.dns.enabled"]
meta = { nidito-acl = "allow altepetl" }

[s3_api]
api_bind_addr = "[::]:{{ env "NOMAD_PORT_s3" }}"
s3_region = "garage"
# used for buckets, i.e. bucket-name.root_domain instead of
# root_domain/bucket
root_domain = "s3.garage.{{ $zone }}"

[s3_web]
bind_addr = "[::]:{{ env "NOMAD_PORT_web" }}"
root_domain = "cajon.{{ $zone }}"

[admin]
{{ with secret (printf "cfg/svc/tree/%s:garage" $zone) }}
api_bind_addr = "0.0.0.0:{{ env "NOMAD_PORT_api" }}"
# metrics_token = "{{ .Data.token.metrics }}"
admin_token = "{{ .Data.token.admin }}"
# trace_sink = "http://localhost:4317"
{{ end }}
