- name: Add the _consul user
  become: true
  user:
    name: "{{ consul_user }}"
    create_home: no
    shell: /usr/bin/false
    groups: _nidito
    append: yes

- name: Install consul
  homebrew:
    name: consul
    state: present

- name: Create the consul directory
  become: true
  file:
    path: "{{ consul_config_dir }}"
    owner: "{{ consul_user }}"
    group: _nidito
    state: directory
    mode: u=rwx,g=rwx,o=

- name: Create the consul log directory
  become: true
  file:
    path: "{{ consul_log_path }}"
    owner: "{{ consul_user }}"
    group: _nidito
    state: directory
    mode: u=rwx,g=rwx,o=

- name: Create the consul var directory
  become: true
  file:
    path: "/var/lib/consul"
    owner: "{{ consul_user }}"
    group: _nidito
    state: directory
    mode: u=rwx,g=rwx,o=

- name: Install consul launchd config
  become: yes
  template:
    src: templates/service.plist.j2
    dest: /Library/LaunchDaemons/io.consul.daemon.plist


