- name: Add the _consul user
  become: true
  user:
    name: "{{ consul_user }}"
    create_home: no
    shell: /usr/bin/false
    groups: _nidito
    append: yes

- name: Get installed version
  shell: consul --version | head -n 1 | cut -dv -f2
  register: installed_consul_version
  ignore_errors: yes
  check_mode: no

- set_fact:
    golang_artifact_arch: "arm64"
  when: node.hardware.arch == 'arm64'

- set_fact:
    golang_artifact_arch: "amd64"
  when: node.hardware.arch == 'x86_64'

- name: Install consul
  when: installed_consul_version.stdout != config.services.consul.version
  notify: Restart consul service
  become: true
  unarchive:
    src: "https://releases.hashicorp.com/consul/{{ config.services.consul.version }}/consul_{{ config.services.consul.version }}_darwin_{{ golang_artifact_arch }}.zip"
    remote_src: yes
    dest: /usr/local/bin

- name: Create the consul directory
  become: true
  file:
    path: "{{ consul_config_dir }}"
    owner: "{{ consul_user }}"
    group: _nidito
    state: directory
    mode: u=rwx,g=rwx,o=

- name: Create the consul log directory
  become: true
  file:
    path: "{{ consul_log_path }}"
    owner: "{{ consul_user }}"
    group: _nidito
    state: directory
    mode: u=rwx,g=rwx,o=

- name: Create the consul var directory
  become: true
  file:
    path: "/var/lib/consul"
    owner: "{{ consul_user }}"
    group: _nidito
    state: directory
    mode: u=rwx,g=rwx,o=

- name: Install consul launchd config
  become: yes
  template:
    src: templates/service.plist.j2
    dest: /Library/LaunchDaemons/io.consul.daemon.plist


