- name: Add the _consul user
  become: true
  user:
    name: "{{ consul.user }}"
    create_home: no
    shell: /usr/bin/false
    groups: "{{ user.group }}"
    append: yes

- name: Install consul
  when: installed_consul_version.stdout != config.services.consul.version
  notify: Restart consul service
  become: true
  unarchive:
    src: "https://releases.hashicorp.com/consul/{{ config.services.consul.version }}/consul_{{ config.services.consul.version }}_darwin_{{ golang_artifact_arch }}.zip"
    remote_src: yes
    dest: "{{ consul.bin | dirname }}"

- name: Create the consul log directory
  become: true
  file:
    path: "{{ consul.logs }}"
    owner: "{{ consul.user }}"
    group: "{{ user.group }}"
    state: directory
    mode: u=rwx,g=rwx,o=

- name: Create the consul data directory
  become: true
  file:
    path: "{{ consul.data }}"
    owner: "{{ consul.user }}"
    group: "{{ user.group }}"
    state: directory
    mode: u=rwx,g=rwx,o=

- name: Install consul launchd config
  become: yes
  template:
    src: templates/service.plist.j2
    dest: /Library/LaunchDaemons/io.consul.daemon.plist


