- name: Restart wireguard service
  when: ansible_pkg_mgr == "pacman"
  listen: restart wireguard
  become: yes
  shell: |
    wg-quick down {{ nidito.wireguard.interface }}
    wg-quick up {{ nidito.wireguard.interface }}
