address: 10.142.20.3
auth:
  username: !!secret
  password: !!secret
dc: qro0
hardware:
  arch: x86_64
  model: vultr-cpu-2x4x50
  os: linux/arch
mac: !!secret
tags:
  role: leader
  storage: secondary
  storage_class: nvme
  reachability: gateway
token:
  consul: !!secret
  consul_replication: !!secret
tls:
  key: !!secret ""
  consul: !!secret ""
  nomad: !!secret ""
  op: !!secret ""
  vault: !!secret ""
