address: 10.42.0.10
ansible:
  command_timeout: 120
  connection: ssh
auth:
  username: !!secret
  password: !!secret
  telemetry:
    username: !!secret
    password: !!secret
dc: casa
hardware:
  arch: arm64
  model: cloudkey-g2-plus
  os: linux/unifios
tags:
  reachability: none
  role: controller
