address: 10.42.20.6
auth:
  username: !!secret
  password: !!secret
dc: casa
hardware:
  arch: arm64
  model: raspberrypi-4b
  os: linux/arch
mac: !!secret
tags:
  role: leader
  storage: none
tls:
  consul: !!secret
  key: !!secret
  nomad: !!secret
  vault: !!secret
token:
  consul: !!secret
