address: 10.42.20.4
auth:
  username: !!secret
  password: !!secret
dc: casa
hardware:
  arch: arm64
  model: mac14,3
  os: macos/sonoma
mac: !!secret
tags:
  role: leader
  storage: secondary
  storage_class: nvme
  builder: enabled
tls:
  key: !!secret ""
  consul: !!secret ""
  nomad: !!secret ""
  op: !!secret ""
  vault: !!secret ""
token:
  consul: !!secret
