address: 10.42.20.7
auth:
  username: !!secret
  password: !!secret
dc: casa
hardware:
  arch: arm64
  model: raspberry-pi-4b
  os: linux/arch
mac: !!secret
tags:
  role: leader
  storage: none
token:
  consul: !!secret
tls:
  key: !!secret ""
  consul: !!secret ""
  nomad: !!secret ""
  op: !!secret ""
  vault: !!secret ""
