- name: Get installed version
  shell: /usr/syno/bin/synopkg version coredns
  register: installed_version
  check_mode: no
  ignore_errors: yes

- set_fact:
    needs_install: "{{ installed_version.stdout != coredns_version }}"

- name: Get coredns SPK
  when: needs_install
  git:
    name: https://github.com/unRob/coredns-spk.git
    dest: /tmp/coredns-spk
    update: no

- name: Get coredns binary
  when: needs_install
  copy:
    src: /tmp/coredns/coredns
    dest: /tmp/coredns-spk/coredns

- name: Create SPK
  when: needs_install
  shell: make coredns.spk

- name: Install SPK
  when: needs_install
  become: true
  shell: /usr/syno/bin/synopkg install /tmp/coredns-spk/coredns.spk

- name: Create the coredns config directory
  when: needs_install
  become: true
  file:
    path: "{{ node.coredns.config }}"
    owner: "{{ node.coredns.user }}"
    state: directory
    mode: u=rwx,g=rwx,o=
