- name: Get installed coredns+consul_catalog plugin version
  become: true
  shell: |
    /config/coredns/coredns -version | awk -F@ '/coredns-consul/ {print $2}'
  register: installed_version
  check_mode: no
  ignore_errors: yes

- set_fact:
    needs_install: "{{ installed_version.stdout != coredns.plugin }}"

- name: Create the coredns directory
  become: true
  file:
    path: "{{ coredns.bin | dirname}}"
    state: directory
    owner: root
    group: vyattacfg
    mode: u=rwx,g=rwx,o=
    recurse: true

- name: Download a coredns+consul build
  when: needs_install and not ansible_check_mode
  become: yes
  unarchive:
    remote_src: yes
    src: "https://github.com/unRob/coredns-consul/releases/download/{{ coredns.plugin }}/coredns-consul-linux-mips64.tgz"
    dest: "{{ coredns.bin | dirname }}"
    mode: u=rwx,g=rwx,o=rw
  notify: restart coredns

- name: Install coredns systemd config backup
  become: true
  template:
    src: templates/coredns.service.j2
    mode: u=rwx,g=rw,o=r
    dest: "{{ coredns.bin | dirname }}/coredns.service"

- name: Create the coredns firstboot directory
  become: true
  file:
    path: "/config/scripts/firstboot.d"
    state: directory
    owner: root
    group: vyattacfg
    mode: u=rwx,g=rwx,o=

- name: Install edgerouter firstboot.d script
  become: true
  template:
    src: templates/post-config.sh
    mode: u=rwx,g=rwx,o=rx
    dest: /config/scripts/firstboot.d/coredns.sh

- name: Run firstboot script
  when: needs_install
  become: true
  shell: /config/scripts/firstboot.d/coredns.sh
