summary: Shows differences between local config values and remote ones
description: |
  runs a diff on remote values vs local ones. expects local config to be unsealed.
options:
  cache:
    description: Don't fetch remote items, store secrets in config/.diff
    type: bool
