summary: Pulls secrets from 1password
description: |
  using magic
arguments:
  - name: item
    description: the 1password item name to get
    required: true
    values:
      milpa: nidito config list
options:
  vault:
    description: the vault name to query in
    default: nidito-admin
    values:
      script: op vault list --format json  | jq -r 'map(.name)[]'
  secrets-only:
    description: merge secrets into config file
    type: bool
  format:
    description: the format to output
    default: json
    values:
      static: [json, yaml]
