- include_tasks: "{{ node.hardware.os }}.yml"

- name: Create config directory
  become: true
  file:
    path: "{{ coredns.config }}/zones"
    state: directory
    recurse: yes

- name: Configure coredns
  become: true
  template:
    src: templates/Corefile.j2
    owner: coredns
    group: users
    dest: "{{ coredns.config }}/Corefile"
    mode: u=rw,g=r,o=
  notify: restart coredns

- name: Install zones
  become: true
  template:
    src: templates/zone.j2
    owner: coredns
    group: users
    dest: "{{ coredns.config }}/zones/main"
    mode: u=rw,g=r,o=
  notify: restart coredns
