- name: Get installed coredns+consul_catalog plugin version
  become: true
  shell: |
    {{ coredns.bin }} -version | awk -F@ '/coredns-consul/ {print $2}'
  register: installed_version
  check_mode: no
  ignore_errors: yes

- set_fact:
    needs_install: "{{ installed_version.stdout != coredns.plugin }}"

- include_tasks: "{{ node.hardware.os }}.yml"

- name: Create directories
  become: true
  file:
    path: "{{ item }}"
    owner: "{{ coredns.user }}"
    group: "{{ coredns.group }}"
    state: directory
    mode: u=rwx,g=rwx,o=
  with_items:
    - "{{ coredns.config }}"
    - "{{ coredns.config }}/zones"

- name: Configure coredns
  become: true
  template:
    src: templates/Corefile.j2
    owner: "{{ coredns.user }}"
    group: "{{ coredns.group }}"
    dest: "{{ coredns.config }}/Corefile"
    mode: u=rw,g=r,o=
  notify: restart coredns

- name: Install zones
  become: true
  template:
    src: "templates/{{ item }}.zone.j2"
    owner: "{{ coredns.user }}"
    group: "{{ coredns.group }}"
    dest: "{{ coredns.config }}/zones/{{ item }}"
    mode: u=rw,g=r,o=
  notify: restart coredns
  with_items:
    - main
    - tepetl
