
---
- name: Base
  hosts:
    - role_router
    - role_leader
  tags: [base, bootstrap]
  roles:
    - base
    - tls-client

- name: CoreDNS
  hosts:
    - role_leader:secondary_dc:reachability_gateway
    - role_router
  tags: [coredns]
  roles:
    - coredns

- name: Wireguard
  hosts:
    - role_leader:secondary_dc:reachability_gateway
    - role_router
  tags: [wireguard]
  roles:
    - wireguard

- name: Telemetry
  hosts:
    - role_leader
    - role_router
    - role_controller
  tags: [bootstrap, telemetry]
  roles:
    - telemetry

- name: Consul
  hosts: role_leader
  tags: [bootstrap, consul]
  serial: 1
  roles:
    - consul-server

- name: Vault
  hosts: role_leader:!storage_none
  tags: [bootstrap, vault]
  serial: 1
  roles:
    - vault-server

- name: Nomad
  hosts: role_leader
  tags: [bootstrap, nomad]
  serial: 1
  roles:
    - docker
    - nomad-server

