
---
# - hosts: reachability_gateway
#   gather_facts: no
#   tasks:
#     - debug:
#         var: rendered_template
#       vars:
#         rendered_template: "{{ lookup('template', './roles/coredns/templates/Corefile.j2') }}"

- hosts: reachability_gateway
  tags: coredns
  gather_facts: no
  roles:
    - gateway
    - coredns
    - wireguard

- hosts: consul_server
  tags: consul
  serial: 1
  roles:
    - consul-server

- hosts: vault_server
  tags: vault
  roles:
    - vault-server

- hosts: nomad_server
  tags: nomad
  roles:
    - nomad-server

