
---
- hosts: role_router
  tags: coredns
  gather_facts: no
  roles:
    # - gateway
    - coredns
    - wireguard

- name: Telemetry
  hosts: role_leader
  tags: [base, telemetry]
  roles:
    - telemetry

- name: Consul
  hosts: role_leader
  tags: [base, consul]
  serial: 1
  roles:
    - role: consul-server

- name: Vault
  hosts: role_leader:!storage_none
  tags: [base, vault]
  roles:
    - vault-server

- name: Nomad
  hosts: role_leader
  tags: [base, nomad]
  roles:
    - nomad-server

