
---
- name: Gateway
  hosts: role_router
  tags: [coredns, wireguard]
  gather_facts: no
  roles:
    - gateway
    - tls-client
    - coredns
    - wireguard

- name: telemetry
  hosts:
    - role_leader
    - role_router
  tags: [telemetry]
  roles:
    - telemetry

- name: Leader node configuration
  hosts: role_leader
  tags: [base]
  roles:
    - server-users
    - tls-client

- name: Consul
  hosts: role_leader
  tags: [consul]
  serial: 1
  roles:
    - role: consul-server

- name: Vault
  hosts: role_leader:!storage_none
  tags: [vault]
  roles:
    - vault-server

- name: Nomad
  hosts: role_leader
  tags: [nomad]
  roles:
    - docker
    - nomad-server

