- hosts: reachability_gateway
  gather_facts: no
  roles:
    - gateway
    - coredns
    - wireguard

- hosts: platform_macos
  roles:
    - server-users

# - hosts: platform_linux_dsm
#   roles:
#     - dsm
#     - plex

# - hosts: all
#   roles:
#     - filebeat

- hosts: consul_server
  roles:
    - consul-server

- hosts: vault_server
  roles:
    - vault-server

- hosts: nomad_server
  roles:
    - nomad-server

