
---
- hosts: role_router
  tags: [coredns, wireguard]
  gather_facts: no
  roles:
    - gateway
    - coredns
    - wireguard

# TODO: figure this shit out... again
- name: telemetry
  hosts: role_leader
  tags: [base, telemetry]
  roles:
    - telemetry

- name: macos
  hosts: os_macos*
  tags: [base]
  roles:
    - server-users

- name: Consul
  hosts: role_leader
  tags: [base, consul]
  serial: 1
  roles:
    - role: consul-server

- name: Vault
  hosts: role_leader:!storage_none
  tags: [base, vault]
  roles:
    - vault-server

- name: Nomad
  hosts: role_leader
  tags: [base, nomad]
  roles:
    - docker
    - nomad-server

