- include_vars: "{{ node.hardware.os }}.yml"

- include: "{{ node.hardware.os }}.yml"

- name: Configure vector
  become: true
  template:
    src: templates/config.toml.j2
    dest: "{{ vector_config_dir }}/vector.toml"
    owner: "{{ vector_user }}"
    mode: u=rw,g=r,o=
  notify: restart vector
