- name: Get installed version
  become: true
  shell: |
    {{ node_exporter.bin }} --version | awk '/^node_exporter/ {print $3}'
  register: node_exporter_installed_version
  check_mode: no
  ignore_errors: yes

- set_fact:
    needs_install: "{{ node_exporter_installed_version.stdout != node_exporter.version }}"

- set_fact:
    golang_artifact_arch: "armv6"
  when: node.hardware.arch == 'arm32'

- set_fact:
    golang_artifact_arch: "arm64"
  when: node.hardware.arch == 'arm64'

- set_fact:
    golang_artifact_arch: "amd64"
  when: node.hardware.arch == 'x86_64'

- include_role:
    name: _service
  vars:
    service_name: node-exporter
    launchd_name: io.prometheus.node_exporter
    launchd_template: templates/service.plist.j2
    systemd_template: templates/node-exporter.service.j2

- include_tasks: "{{ node.hardware.os }}.yml"

# unifi-poller en cloudkey + DPKG_CACHE_UBNT_PKGS en /etc/default/ubnt-dpkg-cache
# prometheus exporter, fuck you all

