summary: builds a service
description: |
  Builds a service by building (and pushing) its Dockerfile, if one is available, or running `make nidito-build` on the current service's working directory.
arguments:
  - name: service
    description: The name of the service to build
    values: { milpa: service list }
options:
  local:
    type: bool
    description: Builds without pushing docker images with the `testing` tag.
